"""Mistfall Hunter 系统要求页面的多语言内容与关键词边界。"""


SYSTEM_REQUIREMENTS_KEYWORD_MAP = {
    "en": {
        "market": "US",
        "primary": "Mistfall Hunter system requirements",
        "related": ["Mistfall Hunter PC requirements", "can I run Mistfall Hunter", "Mistfall Hunter minimum requirements", "Mistfall Hunter recommended specs", "Mistfall Hunter download size"],
        "rejected": ["Mistfall Hunter system requirements lab (navigational brand term)", "Mistfall Hunter console requirements (no verified console PC-spec intent)"],
        "intent": "Informational / pre-purchase compatibility check",
        "evidence": "Similarweb Keyword Generator exact match, global country=999, 2026-08-28 to 2026-09-24; phrase match and related tabs returned the exact term, question tab returned no rows.",
        "confidence": "medium",
    },
    "es": {
        "market": "US / Latin America Spanish audience",
        "primary": "requisitos de sistema de Mistfall Hunter",
        "related": ["requisitos de Mistfall Hunter", "puedo ejecutar Mistfall Hunter", "requisitos minimos Mistfall Hunter", "especificaciones recomendadas Mistfall Hunter", "tamano de Mistfall Hunter"],
        "rejected": ["Mistfall Hunter system requirements lab (brand/navigation wording)", "requisitos de consola Mistfall Hunter (not verified)"],
        "intent": "Informacional / comprobacion de compatibilidad antes de comprar",
        "evidence": "Global Similarweb exact-match English system-requirements cluster; Spanish market inferred from the existing locale, with no Spanish-market Similarweb rows available.",
        "confidence": "low",
    },
    "ja": {
        "market": "Japan",
        "primary": "Mistfall Hunter 必要スペック",
        "related": ["Mistfall Hunter システム要件", "Mistfall Hunter 動作環境", "Mistfall Hunter 最低スペック", "Mistfall Hunter 推奨スペック", "Mistfall Hunter 容量"],
        "rejected": ["Mistfall Hunter system requirements lab (brand/navigation wording)", "Mistfall Hunter console specs (not verified)"],
        "intent": "情報収集 / 購入前の動作環境確認",
        "evidence": "Global Similarweb exact-match English system-requirements cluster; Japanese market inferred from the existing locale, with no Japanese-market Similarweb rows available.",
        "confidence": "low",
    },
    "fr": {
        "market": "France",
        "primary": "configuration requise Mistfall Hunter",
        "related": ["configuration PC Mistfall Hunter", "Mistfall Hunter peut-il tourner", "configuration minimale Mistfall Hunter", "configuration recommandee Mistfall Hunter", "taille de Mistfall Hunter"],
        "rejected": ["Mistfall Hunter system requirements lab (brand/navigation wording)", "configuration console Mistfall Hunter (not verified)"],
        "intent": "Information / verifier la compatibilite avant achat",
        "evidence": "Global Similarweb exact-match English system-requirements cluster; French market inferred from the existing locale, with no French-market Similarweb rows available.",
        "confidence": "low",
    },
    "de": {
        "market": "Germany",
        "primary": "Mistfall Hunter Systemanforderungen",
        "related": ["Mistfall Hunter PC Anforderungen", "Kann ich Mistfall Hunter spielen", "minimale Anforderungen Mistfall Hunter", "empfohlene Anforderungen Mistfall Hunter", "Mistfall Hunter Speicherplatz"],
        "rejected": ["Mistfall Hunter system requirements lab (brand/navigation wording)", "Mistfall Hunter Konsolenanforderungen (not verified)"],
        "intent": "Informativ / Kompatibilitat vor dem Kauf prufen",
        "evidence": "Global Similarweb exact-match English system-requirements cluster; German market inferred from the existing locale, with no German-market Similarweb rows available.",
        "confidence": "low",
    },
    "pt": {
        "market": "Brazil",
        "primary": "requisitos de sistema de Mistfall Hunter",
        "related": ["requisitos para PC Mistfall Hunter", "Mistfall Hunter roda no meu PC", "requisitos minimos Mistfall Hunter", "requisitos recomendados Mistfall Hunter", "tamanho de Mistfall Hunter"],
        "rejected": ["Mistfall Hunter system requirements lab (brand/navigation wording)", "requisitos de console Mistfall Hunter (not verified)"],
        "intent": "Informacional / checagem de compatibilidade antes da compra",
        "evidence": "Global Similarweb exact-match English system-requirements cluster; Brazilian Portuguese market inferred from the existing locale, with no Portuguese-market Similarweb rows available.",
        "confidence": "low",
    },
    "ko": {
        "market": "South Korea",
        "primary": "Mistfall Hunter 시스템 요구 사항",
        "related": ["Mistfall Hunter PC 사양", "Mistfall Hunter 실행 가능 여부", "Mistfall Hunter 최소 사양", "Mistfall Hunter 권장 사양", "Mistfall Hunter 용량"],
        "rejected": ["Mistfall Hunter system requirements lab (brand/navigation wording)", "Mistfall Hunter 콘솔 사양 (not verified)"],
        "intent": "정보 탐색 / 구매 전 호환성 확인",
        "evidence": "Global Similarweb exact-match English system-requirements cluster; Korean market inferred from the existing locale, with no Korean-market Similarweb rows available.",
        "confidence": "low",
    },
    "it": {
        "market": "Italy",
        "primary": "requisiti di sistema Mistfall Hunter",
        "related": ["requisiti PC Mistfall Hunter", "Mistfall Hunter gira sul mio PC", "requisiti minimi Mistfall Hunter", "requisiti consigliati Mistfall Hunter", "spazio richiesto Mistfall Hunter"],
        "rejected": ["Mistfall Hunter system requirements lab (brand/navigation wording)", "requisiti console Mistfall Hunter (not verified)"],
        "intent": "Informativo / controllo compatibilita prima dell acquisto",
        "evidence": "Global Similarweb exact-match English system-requirements cluster; Italian market inferred from the existing locale, with no Italian-market Similarweb rows available.",
        "confidence": "low",
    },
}


SYSTEM_REQUIREMENTS_PAGE_DATA = {
    "en": {
        "page": {"title": "Mistfall Hunter System Requirements: Can Your PC Run It?", "description": "Check the official Mistfall Hunter minimum and recommended PC requirements, storage, SSD note, and practical steps before you buy or install.", "h1": "Mistfall Hunter System Requirements: Minimum and Recommended PC Specs", "kicker": "System requirements guide | Official Steam check: 24 September 2026"},
        "sections": [
            {"type": "rich", "title": "Quick answer: check the official rows first", "paragraphs": [
                "The official Steam listing currently asks for Windows 10 64 bit, 12 GB of RAM, a GTX 1060 or Radeon RX 580 class graphics card, DirectX 12, broadband internet, and 45 GB of available storage at minimum. The recommended row moves to 16 GB of RAM and an RTX 2070 or Radeon RX 5700 XT class GPU. Both rows repeat the SSD recommendation.",
                "Those figures answer the compatibility question, but they do not promise a fixed frame rate. A minimum requirement is a store-side baseline for starting the game, not a guarantee that every scene will feel smooth at a chosen resolution. Driver versions, background software, thermals, laptop power limits, resolution, graphics settings, and the size of a future patch can all change the result.",
                "Use this page as a pre-purchase checklist. Compare your actual processor, graphics card, memory, operating system, and free space with the table below, then open the official Steam page for the latest wording. This fan guide does not distribute files or claim to certify a PC that has not been tested in the game."
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": "Official Mistfall Hunter Steam artwork showing hunters crossing a snowy battlefield", "caption": "Official Steam artwork for Mistfall Hunter. It identifies the game covered by this system-requirements guide; it is not a performance benchmark.", "width": 1280, "height": 360},
            {"type": "table", "title": "Official Mistfall Hunter PC requirements", "headers": ["Component", "Minimum", "Recommended", "How to read it"], "rows": [
                ["Operating system", "Windows 10 64 bit", "Windows 10 64 bit", "A 64-bit Windows install is required in both rows."],
                ["Processor", "Intel Core i7-4770 / AMD Ryzen 5 1400", "Intel Core i7-9700 / AMD Ryzen 5 3600", "Compare the model, not only the brand or advertised boost clock."],
                ["Memory", "12 GB RAM", "16 GB RAM", "Leave headroom for Windows, a browser, voice chat, and background tools."],
                ["Graphics", "NVIDIA GTX 1060 / AMD RX 580", "NVIDIA RTX 2070 / AMD RX 5700 XT", "GPU generation, VRAM, drivers, and laptop power limits still matter."],
                ["DirectX", "Version 12", "Version 12", "Keep Windows and the graphics driver current before troubleshooting."],
                ["Network", "Broadband internet", "Broadband internet", "The listing gives no stable bandwidth target; connection quality affects online play."],
                ["Storage", "45 GB available space", "45 GB available space", "Free space is not the same as the installed game size after updates."],
                ["Additional note", "SSD strongly recommended", "SSD strongly recommended", "An SSD can reduce loading friction, but it does not upgrade a weak GPU."],
            ]},
            {"type": "rich", "title": "How to compare your PC without guessing", "paragraphs": [
                "Start with the graphics card because the minimum and recommended rows show the largest practical jump there. Search the exact GPU model in Windows Task Manager or the vendor control panel. A name such as “RTX” or “Radeon” is not enough by itself: two cards in the same family can have different memory, laptop wattage, and cooling limits. Desktop and laptop versions should be treated as separate comparisons.",
                "Then check the processor and memory. The minimum CPU row is older than the recommended row, so a machine can meet the named GPU line while still feeling limited by CPU-heavy scenes or background work. Twelve gigabytes of RAM is the store baseline; if Windows, a browser, Discord, recording software, or an overlay already consumes several gigabytes, 16 GB gives a more comfortable margin.",
                "Finally, confirm storage and the operating system. Keep more than the listed 45 GB free if your drive is nearly full, because patches, shader caches, and Windows updates also need working room. Installing on an SSD follows the store's explicit note. It can improve load times and reduce texture-streaming friction, but it cannot turn a below-minimum CPU or GPU into a recommended system."
            ], "subsections": [
                ["CPU: compare the exact model", ["Use the full model name from Task Manager, BIOS, or a trusted hardware utility. A newer mid-range CPU may behave differently from an older high-end chip even when the names look similar. Treat the official model rows as reference points rather than a universal ranking." ]],
                ["GPU: desktop, laptop, and VRAM are not interchangeable", ["Check whether your card is a laptop variant and note its dedicated memory. A laptop GPU with the same label can have a lower power limit. If your card is close to the minimum, plan to test low settings and a conservative resolution before carrying valuable gear into a long run." ]],
                ["RAM and storage: leave operating room", ["The game needs memory and disk space at the same time as Windows and your normal tools. Close unnecessary launchers, keep the drive comfortably below full, and avoid treating the exact 45 GB number as a permanent update budget." ]],
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-system-requirements-pc.webp", "alt": "Official Mistfall Hunter Steam screenshot of a hunter facing a luminous tree in a forest", "caption": "Official Steam store screenshot. The scene shows the kind of dark-fantasy environment the PC must render; it does not establish FPS, resolution, or graphics settings.", "width": 960, "height": 540},
            {"type": "rich", "title": "What the requirements do not tell you", "paragraphs": [
                "Steam's requirements do not publish a target frame rate, resolution, preset, ray-tracing mode, or VRAM recommendation. They also do not say how performance changes in a busy extraction, during a boss encounter, or after a content patch. That is why a PC that technically passes the minimum row may still need a settings pass before a serious session.",
                "Online play adds another variable. The listing asks for broadband internet, but a single bandwidth number would not capture ping, jitter, packet loss, Wi-Fi interference, or regional matchmaking. If combat feels delayed, separate a local frame-rate problem from a network problem before replacing hardware. The player-count guide can help you think about queue timing; this page is about local compatibility.",
                "Use community performance reports as examples, not guarantees. Match the report to your CPU, GPU, RAM, resolution, driver, and settings. A video made on a desktop RTX card cannot certify a thin laptop with the same product family name. Record your own temperatures, frame pacing, and settings during a low-risk test run, then decide whether the result is acceptable for your play style."
            ]},
            {"type": "table", "title": "Compatibility decisions after the first comparison", "headers": ["Your situation", "Practical next step", "Reason"], "rows": [
                ["Below the minimum CPU or GPU", "Do not treat the page as a pass; upgrade or wait for verified testing.", "The official baseline is already missed."],
                ["Meets minimum, but only 12 GB RAM", "Close background apps and test before buying extra hardware.", "Memory headroom may be the limiting factor."],
                ["Meets GPU and CPU, but drive is nearly full", "Free space and install on an SSD when possible.", "Patches and caches also need working room."],
                ["Meets recommended on a laptop", "Check power mode, thermals, and the exact mobile GPU.", "Laptop variants can perform below desktop equivalents."],
                ["Specs are unknown", "Read the model names from Windows before deciding.", "A vague “gaming PC” label is not a comparable specification."],
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-system-requirements-combat.webp", "alt": "Official Mistfall Hunter Steam screenshot of a hunter approaching a chest in a dark stone chamber", "caption": "Official Steam store screenshot used as visual context for the rendering workload. It is not a benchmark or a claim about minimum settings.", "width": 960, "height": 540},
            {"type": "rich", "title": "A five-minute pre-install check", "paragraphs": [
                "1. Open Windows Settings or Task Manager and copy the exact Windows edition, CPU model, installed RAM, and GPU model. 2. Compare each line with the official table rather than relying on a single benchmark score. 3. Confirm at least 45 GB is free and prefer an SSD with additional room for updates. 4. Update the graphics driver and Windows, then close overlays that you do not need. 5. If you are near the minimum, plan a short low-risk run to observe frame pacing and temperatures before judging the game.",
                "Do not confuse the official store requirements with a download promise. The listing is the authoritative place to verify the current game package, price, platform, and requirement text. This site links to Steam for that reason and does not provide a mirror, key, installer, or safety scan. If the store changes the numbers, use the live official page over an older guide snapshot.",
                "The useful decision is not simply “can it launch?” Ask whether the machine can launch, keep a stable enough frame rate for your preferred fights, and leave room for the extraction decisions that make Mistfall Hunter demanding. When the answer is uncertain, lower the risk of the test: use a safe class direction from the class guide, avoid carrying irreplaceable gear, and write down what changed after every setting adjustment."
            ], "subsections": [
                ["What to record during a test", ["Note resolution, preset, frame-rate cap, GPU usage, CPU usage, temperatures, and whether the issue is a hitch, a low average, or a network delay. One observation is not a universal benchmark, but it gives you a useful baseline for your own machine." ]],
                ["When to re-check", ["Revisit the official Steam requirements after a major patch, a driver change, a hardware upgrade, or a move from desktop to laptop. Requirements can stay the same while real-world performance shifts with content and software updates." ]],
            ]},
            {"type": "faq", "title": "Mistfall Hunter system requirements FAQ", "items": [
                ["What are the minimum Mistfall Hunter system requirements?", "The official Steam listing currently names Windows 10 64 bit, an Intel Core i7-4770 or AMD Ryzen 5 1400, 12 GB RAM, a GTX 1060 or RX 580 class GPU, DirectX 12, broadband internet, and 45 GB available space. An SSD is strongly recommended."],
                ["What are the recommended specs for Mistfall Hunter?", "The recommended row lists Windows 10 64 bit, an Intel Core i7-9700 or AMD Ryzen 5 3600, 16 GB RAM, an RTX 2070 or RX 5700 XT class GPU, DirectX 12, broadband internet, and 45 GB available space. The SSD note also applies."],
                ["Can I run Mistfall Hunter with 12 GB of RAM?", "Twelve gigabytes meets the official minimum row, but available headroom matters. Close unnecessary apps and test frame pacing on your own PC. Meeting a store baseline is not a fixed FPS guarantee."],
                ["Does Mistfall Hunter require an SSD?", "The Steam listing strongly recommends an SSD for a better experience. It is presented as an additional note rather than a separate capacity requirement; an SSD can help loading and streaming but cannot replace missing CPU or GPU capability."],
                ["How much storage does Mistfall Hunter need?", "The current official listing says 45 GB of available space. Keep extra room for updates, shader caches, and Windows because available space can shrink after installation."],
                ["Are these requirements a guarantee for 60 FPS?", "No. Steam does not attach a fixed FPS, resolution, or graphics preset to these rows. Treat them as compatibility guidance and check settings, thermals, drivers, and network conditions on your own system."],
            ]},
            {"type": "links", "title": "Official verification source", "items": [["Mistfall Hunter on Steam", "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", "First-party product page, current PC requirements, platform facts, price, reviews, and screenshot gallery.", "noopener"]]},
        ],
    },
}


def _localized_copy(locale):
    """
    返回指定 locale 的系统要求页面本地化文案。

    :param locale: 语言代码
    :return: dict，页面元数据、正文区块和本地化关键词
    """
    return SYSTEM_REQUIREMENTS_PAGE_DATA.get(locale) or SYSTEM_REQUIREMENTS_PAGE_DATA["en"]


def _clone_with_locale(locale, page, sections):
    """
    根据 locale 复制页面结构并附加关键词元数据。

    :param locale: 语言代码
    :param page: 页面元数据
    :param sections: 页面正文区块
    :return: dict，完整页面数据
    """
    keyword = SYSTEM_REQUIREMENTS_KEYWORD_MAP[locale]
    return {"page": page, "sections": sections, "keyword_map": keyword}


def build_system_requirements_page_data():
    """
    生成所有首页 locale 的系统要求页面数据。

    :return: dict，locale 到页面数据的映射
    """
    data = {"en": _clone_with_locale("en", SYSTEM_REQUIREMENTS_PAGE_DATA["en"]["page"], SYSTEM_REQUIREMENTS_PAGE_DATA["en"]["sections"])}
    localized = {
        "es": {
            "title": "Requisitos de sistema de Mistfall Hunter: ¿puede ejecutarlo tu PC?",
            "description": "Consulta los requisitos mínimos y recomendados oficiales de Mistfall Hunter, el espacio, el SSD y una lista práctica antes de comprar.",
            "h1": "Requisitos de sistema de Mistfall Hunter: configuración mínima y recomendada",
            "kicker": "Guía de requisitos | Comprobación oficial de Steam: 24 de septiembre de 2026",
            "quick_title": "Respuesta rápida: empieza por la tabla oficial",
            "quick": ["La página oficial de Steam indica Windows 10 de 64 bits, 12 GB de RAM, una GTX 1060 o Radeon RX 580, DirectX 12, internet de banda ancha y 45 GB libres como mínimo. La fila recomendada sube a 16 GB de RAM y una RTX 2070 o Radeon RX 5700 XT. En ambas aparece la recomendación de instalar en SSD.", "Estos datos responden a la compatibilidad, pero no garantizan una tasa de frames concreta. Un requisito mínimo es una referencia de la tienda, no una promesa de fluidez a una resolución determinada. Controladores, temperatura, programas en segundo plano, límites de energía del portátil, ajustes y parches pueden cambiar el resultado.", "Usa esta página como lista de compra e instalación. Compara tu procesador, gráfica, memoria, sistema y espacio reales con la tabla, y abre Steam para confirmar el texto vigente. Esta guía de fans no distribuye archivos ni certifica un equipo que no haya sido probado en el juego."],
            "image1_alt": "Arte oficial de Steam de Mistfall Hunter con cazadores cruzando un campo nevado", "image1_caption": "Arte oficial de Steam para identificar el juego de esta guía. No es una prueba de rendimiento.",
            "table_title": "Requisitos oficiales de Mistfall Hunter para PC", "table_headers": ["Componente", "Mínimo", "Recomendado", "Cómo leerlo"],
            "table_rows": [["Sistema operativo", "Windows 10 de 64 bits", "Windows 10 de 64 bits", "Las dos filas exigen una instalación de 64 bits."], ["Procesador", "Intel Core i7-4770 / AMD Ryzen 5 1400", "Intel Core i7-9700 / AMD Ryzen 5 3600", "Compara el modelo exacto, no solo la marca."], ["Memoria", "12 GB RAM", "16 GB RAM", "Deja margen para Windows, navegador y chat de voz."], ["Gráfica", "NVIDIA GTX 1060 / AMD RX 580", "NVIDIA RTX 2070 / AMD RX 5700 XT", "También importan memoria, drivers y potencia del portátil."], ["DirectX", "Versión 12", "Versión 12", "Actualiza Windows y el driver gráfico antes de probar."], ["Red", "Internet de banda ancha", "Internet de banda ancha", "La ficha no fija una velocidad; la calidad afecta al online."], ["Almacenamiento", "45 GB libres", "45 GB libres", "El espacio libre no es un presupuesto permanente de parches."], ["Nota", "SSD muy recomendado", "SSD muy recomendado", "Un SSD ayuda con cargas, no sustituye una gráfica débil."]],
            "compare_title": "Cómo comparar tu PC sin adivinar", "compare": ["Empieza por la gráfica porque el salto entre mínimo y recomendado es importante. Busca el modelo exacto en el Administrador de tareas o en el panel del fabricante. Decir solo “RTX” o “Radeon” no basta: dos tarjetas pueden tener distinta memoria, refrigeración y potencia, y las versiones de portátil no deben compararse automáticamente con las de sobremesa.", "Después revisa procesador y memoria. Un equipo puede alcanzar la línea de GPU y quedarse corto en escenas con mucha carga de CPU o con programas abiertos. Doce gigabytes es la base de la tienda; si Windows, navegador, Discord, grabación u overlays consumen memoria, 16 GB ofrecen un margen más cómodo.", "Por último, comprueba sistema y espacio. Mantén más de 45 GB libres si el disco está casi lleno porque los parches, cachés y actualizaciones también necesitan sitio. El SSD sigue la nota explícita de Steam: mejora cargas, pero no convierte una CPU o GPU inferior al mínimo en una configuración recomendada."],
            "image2_alt": "Captura oficial de Steam de Mistfall Hunter con un cazador ante un árbol luminoso", "image2_caption": "Captura oficial de la tienda de Steam. Muestra un entorno que el PC debe renderizar, pero no fija FPS, resolución ni ajustes.",
            "limits_title": "Lo que los requisitos no cuentan", "limits": ["Steam no publica FPS objetivo, resolución, preset, trazado de rayos ni VRAM. Tampoco explica el rendimiento en una extracción llena, un jefe o después de un parche. Un equipo que pasa el mínimo puede necesitar una prueba de ajustes antes de una sesión importante.", "La conexión también importa. “Banda ancha” no resume ping, jitter, pérdida de paquetes o interferencias Wi-Fi. Si el combate responde tarde, separa un problema local de frames de un problema de red antes de cambiar hardware.", "Los informes de la comunidad sirven como ejemplos, no como garantía. Compara CPU, GPU, RAM, resolución, drivers y ajustes del informe con tu equipo. Mide temperaturas y estabilidad durante una prueba de bajo riesgo y decide con tus propios datos."],
            "image3_alt": "Captura oficial de Steam de Mistfall Hunter con un cazador acercándose a un cofre en una cámara oscura", "image3_caption": "Captura oficial de Steam como contexto visual del trabajo de renderizado. No es un benchmark.",
            "check_title": "Comprobación de cinco minutos antes de instalar", "check": ["1. Abre Configuración de Windows o el Administrador de tareas y copia la edición, CPU, RAM y GPU exactas. 2. Compara cada línea con la tabla oficial. 3. Confirma 45 GB libres y, si puedes, instala en SSD con espacio adicional. 4. Actualiza driver y Windows y cierra overlays innecesarios. 5. Si estás cerca del mínimo, prueba una partida corta y de bajo riesgo para observar estabilidad y temperaturas.", "No confundas la ficha oficial con una promesa de descarga. Steam es la fuente para paquete, precio, plataforma y requisitos actuales. Este sitio enlaza allí y no ofrece mirrors, claves, instaladores ni análisis de seguridad. Si cambian las cifras, manda la página oficial sobre una guía antigua.", "La pregunta útil no es solo “¿arranca?”. Pregunta si puede arrancar, mantener una tasa de frames suficiente para tus combates y dejar margen para las decisiones de extracción. Si dudas, reduce el riesgo: usa una clase segura, evita llevar equipo irremplazable y anota qué cambia con cada ajuste."],
            "faq_title": "Preguntas frecuentes sobre los requisitos de Mistfall Hunter", "faq": [["¿Cuáles son los requisitos mínimos?", "Steam indica Windows 10 de 64 bits, i7-4770 o Ryzen 5 1400, 12 GB RAM, GTX 1060 o RX 580, DirectX 12, banda ancha y 45 GB libres. También recomienda SSD."], ["¿Cuáles son los recomendados?", "La fila recomendada usa i7-9700 o Ryzen 5 3600, 16 GB RAM, RTX 2070 o RX 5700 XT, DirectX 12, banda ancha y 45 GB. El SSD sigue recomendado."], ["¿Puedo jugar con 12 GB de RAM?", "Cumples la fila mínima, pero cierra programas y prueba tu equipo. Cumplir la ficha no fija los FPS."], ["¿Hace falta SSD?", "Steam lo recomienda mucho para mejorar la experiencia. Ayuda con cargas, pero no reemplaza CPU o GPU suficientes."], ["¿Cuánto espacio ocupa?", "La ficha actual dice 45 GB disponibles. Deja margen adicional para parches, cachés y Windows."], ["¿Garantiza 60 FPS?", "No. Steam no ata estas filas a FPS, resolución o preset; comprueba tu propio sistema."]],
            "source_title": "Fuente oficial de verificación", "source_desc": "Página oficial de Steam con requisitos, plataforma, precio, reseñas y galería.", "related_title": "Guías relacionadas de Mistfall Hunter",
        },
        "fr": {
            "title": "Configuration requise de Mistfall Hunter : votre PC peut-il le faire tourner ?",
            "description": "Consultez la configuration minimale et recommandée officielle de Mistfall Hunter, l espace disque, le SSD et les limites de performance avant achat.",
            "h1": "Configuration requise de Mistfall Hunter : PC minimum et recommandé",
            "kicker": "Configuration requise | Vérification Steam officielle : 24 septembre 2026",
            "quick_title": "Réponse rapide : commencez par les lignes officielles",
            "quick": ["La fiche Steam officielle demande actuellement Windows 10 64 bits, 12 Go de RAM, une GTX 1060 ou Radeon RX 580, DirectX 12, une connexion haut débit et 45 Go libres au minimum. La ligne recommandée passe à 16 Go de RAM et une RTX 2070 ou Radeon RX 5700 XT. Les deux lignes conseillent un SSD.", "Ces chiffres répondent à la compatibilité, mais ne promettent pas une fréquence d images fixe. Une configuration minimale est une base publiée par la boutique, pas une garantie de fluidité à une résolution précise. Les pilotes, températures, logiciels ouverts, limites d un portable, réglages et mises à jour changent le résultat.", "Utilisez cette page comme une checklist avant achat. Comparez le processeur, la carte graphique, la mémoire, Windows et l espace libre de votre machine avec le tableau, puis vérifiez la page Steam actuelle. Ce site fan-made ne fournit ni fichiers ni certification de PC non testé."],
            "image1_alt": "Illustration Steam officielle de Mistfall Hunter avec des chasseurs sur un champ enneigé", "image1_caption": "Illustration officielle Steam pour identifier le jeu. Elle ne constitue pas un benchmark.",
            "table_title": "Configuration PC officielle de Mistfall Hunter", "table_headers": ["Composant", "Minimum", "Recommandé", "Lecture pratique"],
            "table_rows": [["Système", "Windows 10 64 bits", "Windows 10 64 bits", "Les deux lignes demandent une installation 64 bits."], ["Processeur", "Intel Core i7-4770 / AMD Ryzen 5 1400", "Intel Core i7-9700 / AMD Ryzen 5 3600", "Comparez le modèle exact, pas seulement la marque."], ["Mémoire", "12 Go RAM", "16 Go RAM", "Gardez une marge pour Windows, navigateur et voix."], ["Graphique", "NVIDIA GTX 1060 / AMD RX 580", "NVIDIA RTX 2070 / AMD RX 5700 XT", "La mémoire, les pilotes et le portable comptent aussi."], ["DirectX", "Version 12", "Version 12", "Mettez Windows et le pilote graphique à jour."], ["Réseau", "Connexion haut débit", "Connexion haut débit", "Aucune vitesse fixe n est publiée; la qualité compte."], ["Stockage", "45 Go disponibles", "45 Go disponibles", "L espace libre n est pas un budget de mises à jour."], ["Note", "SSD fortement conseillé", "SSD fortement conseillé", "Le SSD aide les chargements, pas un GPU faible."]],
            "compare_title": "Comparer son PC sans deviner", "compare": ["Commencez par la carte graphique, car l écart entre minimum et recommandé est le plus visible. Relevez le modèle exact dans le Gestionnaire des tâches ou le panneau du fabricant. “RTX” ou “Radeon” ne suffit pas : mémoire, refroidissement et puissance diffèrent, surtout entre une version portable et une version de bureau.", "Vérifiez ensuite le processeur et la mémoire. Une machine peut atteindre la ligne GPU et rester limitée dans une scène chargée par le CPU ou avec plusieurs programmes ouverts. Douze gigaoctets est la base Steam; si Windows, le navigateur, Discord, l enregistrement ou les overlays consomment déjà de la mémoire, 16 Go offrent davantage de marge.", "Enfin, confirmez Windows et le disque. Gardez plus de 45 Go libres si le disque est presque plein, car les correctifs, caches et mises à jour ont aussi besoin d espace. Le SSD suit la note Steam : il peut réduire les chargements, mais ne transforme pas un processeur ou un GPU sous le minimum en configuration recommandée."],
            "image2_alt": "Capture officielle Steam de Mistfall Hunter montrant un chasseur devant un arbre lumineux", "image2_caption": "Capture officielle de la boutique Steam. Elle illustre un environnement à rendre, sans fixer les FPS ni les réglages.",
            "limits_title": "Ce que la configuration ne dit pas", "limits": ["Steam ne publie ni FPS cible, ni résolution, ni preset, ni mode ray tracing, ni recommandation VRAM. La fiche ne décrit pas non plus une extraction chargée, un boss ou un patch. Un PC qui passe le minimum peut donc demander un réglage avant une vraie session.", "Le réseau ajoute une variable. “Haut débit” ne résume pas la latence, le jitter, la perte de paquets ou le Wi-Fi. Si le combat semble en retard, séparez un souci d images local d un souci réseau avant de remplacer du matériel.", "Les rapports de communauté sont des exemples, pas des garanties. Comparez CPU, GPU, RAM, résolution, pilotes et réglages avec votre machine. Notez températures et stabilité pendant un test peu risqué, puis décidez avec vos propres mesures."],
            "image3_alt": "Capture officielle Steam de Mistfall Hunter montrant un chasseur près d un coffre dans une salle sombre", "image3_caption": "Capture officielle Steam utilisée comme contexte visuel, pas comme benchmark.",
            "check_title": "Vérification de cinq minutes avant l installation", "check": ["1. Relevez dans Windows l édition, le processeur, la RAM et le GPU exacts. 2. Comparez chaque ligne au tableau officiel. 3. Confirmez 45 Go libres et préférez un SSD avec de la marge. 4. Mettez Windows et le pilote à jour et fermez les overlays inutiles. 5. Près du minimum, faites un test court et peu risqué pour observer la stabilité et les températures.", "Ne confondez pas les exigences officielles avec une promesse de téléchargement. Steam reste la source pour le paquet, le prix, la plateforme et le texte actuel. Ce site y renvoie et ne propose ni miroir, ni clé, ni installateur, ni scan de sécurité. Si les chiffres changent, la page officielle prime sur un ancien article.", "La bonne question n est pas seulement « est-ce que le jeu démarre ? ». Demandez-vous s il démarre, garde une fluidité suffisante pour vos combats et laisse de la marge aux décisions d extraction. En cas de doute, testez avec une classe sûre, peu d équipement et des notes sur chaque réglage."],
            "faq_title": "Questions fréquentes sur la configuration de Mistfall Hunter", "faq": [["Quelle est la configuration minimale ?", "Steam indique Windows 10 64 bits, i7-4770 ou Ryzen 5 1400, 12 Go RAM, GTX 1060 ou RX 580, DirectX 12, haut débit et 45 Go libres. Le SSD est fortement conseillé."], ["Quelle est la configuration recommandée ?", "La ligne recommandée utilise i7-9700 ou Ryzen 5 3600, 16 Go RAM, RTX 2070 ou RX 5700 XT, DirectX 12, haut débit et 45 Go. Le SSD reste conseillé."], ["Puis-je jouer avec 12 Go de RAM ?", "Cela correspond au minimum officiel. Fermez les programmes inutiles et testez votre machine; le minimum ne fixe pas les FPS."], ["Un SSD est-il obligatoire ?", "Steam le conseille fortement pour une meilleure expérience. Il aide les chargements mais ne remplace pas un CPU ou GPU suffisant."], ["Combien d espace faut-il ?", "La fiche actuelle annonce 45 Go disponibles. Gardez de la marge pour les mises à jour, caches et Windows."], ["Ces lignes garantissent-elles 60 FPS ?", "Non. Aucun FPS, résolution ou preset n est associé aux lignes; vérifiez votre propre environnement."]],
            "source_title": "Source officielle", "source_desc": "Page Steam officielle avec exigences, plateforme, prix, avis et captures.", "related_title": "Ressources Mistfall Hunter associées",
        },
        "de": {
            "title": "Mistfall Hunter Systemanforderungen: Schafft dein PC das Spiel?",
            "description": "Prüfe die offiziellen minimalen und empfohlenen PC-Anforderungen von Mistfall Hunter, Speicherplatz, SSD-Hinweis und praktische Kaufchecks.",
            "h1": "Mistfall Hunter Systemanforderungen: Minimale und empfohlene PC-Specs",
            "kicker": "Anforderungsprüfung | Offizieller Steam-Check: 24.09.2026",
            "quick_title": "Kurzantwort: zuerst die offiziellen Zeilen prüfen",
            "quick": ["Die offizielle Steam-Seite nennt derzeit Windows 10 64 Bit, 12 GB RAM, eine GTX 1060 oder Radeon RX 580, DirectX 12, Breitband-Internet und 45 GB freien Speicher als Minimum. Für die Empfehlung werden 16 GB RAM sowie eine RTX 2070 oder Radeon RX 5700 XT genannt. Beide Zeilen empfehlen eine SSD.", "Diese Werte beantworten die Kompatibilitätsfrage, garantieren aber keine feste Bildrate. Mindestanforderungen sind eine Store-Basis und kein Versprechen für eine bestimmte Auflösung. Treiber, Temperaturen, Hintergrundprogramme, Notebook-Leistung, Einstellungen und Patches verändern das Ergebnis.", "Nutze die Seite als Checkliste vor Kauf und Installation. Vergleiche Prozessor, Grafikkarte, RAM, Windows und freien Speicher mit der Tabelle und öffne danach Steam für den aktuellen Wortlaut. Diese Fan-Seite verteilt keine Dateien und zertifiziert keinen ungetesteten PC."],
            "image1_alt": "Offizielles Mistfall-Hunter-Steam-Artwork mit Jägern auf einem verschneiten Schlachtfeld", "image1_caption": "Offizielles Steam-Artwork zur Identifikation des Spiels. Es ist kein Performance-Benchmark.",
            "table_title": "Offizielle Mistfall Hunter PC-Anforderungen", "table_headers": ["Komponente", "Minimum", "Empfohlen", "Praktische Einordnung"],
            "table_rows": [["Betriebssystem", "Windows 10 64 Bit", "Windows 10 64 Bit", "Beide Zeilen benötigen ein 64-Bit-System."], ["Prozessor", "Intel Core i7-4770 / AMD Ryzen 5 1400", "Intel Core i7-9700 / AMD Ryzen 5 3600", "Das genaue Modell zählt, nicht nur die Marke."], ["Arbeitsspeicher", "12 GB RAM", "16 GB RAM", "Lass Platz für Windows, Browser und Sprachchat."], ["Grafik", "NVIDIA GTX 1060 / AMD RX 580", "NVIDIA RTX 2070 / AMD RX 5700 XT", "VRAM, Treiber und Notebook-Leistung zählen ebenfalls."], ["DirectX", "Version 12", "Version 12", "Windows und Grafiktreiber vor dem Test aktualisieren."], ["Netzwerk", "Breitband-Internet", "Breitband-Internet", "Steam nennt keine feste Geschwindigkeit; Qualität zählt."], ["Speicher", "45 GB frei", "45 GB frei", "Freier Platz ist kein dauerhaftes Update-Budget."], ["Zusatz", "SSD stark empfohlen", "SSD stark empfohlen", "Eine SSD hilft bei Ladezeiten, ersetzt aber keine schwache GPU."]],
            "compare_title": "Den eigenen PC ohne Raten vergleichen", "compare": ["Beginne mit der Grafikkarte, weil der Abstand zwischen Minimum und Empfehlung dort am deutlichsten ist. Lies das genaue Modell im Task-Manager oder beim Hersteller aus. Nur „RTX“ oder „Radeon“ reicht nicht: Speicher, Kühlung und Leistungsgrenzen unterscheiden sich, besonders zwischen Desktop- und Notebook-Versionen.", "Prüfe danach CPU und RAM. Ein Rechner kann die GPU-Zeile erfüllen und in CPU-lastigen Szenen oder mit offenen Programmen trotzdem an Grenzen kommen. Zwölf Gigabyte sind die Steam-Basis; wenn Windows, Browser, Discord, Aufnahme oder Overlays bereits RAM nutzen, geben 16 GB mehr Spielraum.", "Kontrolliere zuletzt System und Laufwerk. Lass mehr als 45 GB frei, wenn der Datenträger fast voll ist, denn Patches, Shader-Caches und Windows brauchen ebenfalls Platz. Die SSD-Empfehlung verbessert Ladezeiten, macht aber keine unter dem Minimum liegende CPU oder GPU zu einem empfohlenen System."],
            "image2_alt": "Offizieller Mistfall-Hunter-Steam-Screenshot mit einem Jäger vor einem leuchtenden Baum", "image2_caption": "Offizieller Steam-Screenshot. Er zeigt eine zu rendernde Umgebung, legt aber keine FPS oder Einstellungen fest.",
            "limits_title": "Was die Anforderungen nicht sagen", "limits": ["Steam nennt keine Ziel-FPS, Auflösung, Preset, Raytracing-Option oder VRAM-Empfehlung. Die Seite beschreibt auch keine volle Extraktion, keinen Boss und keinen Patch. Ein PC über dem Minimum kann daher noch einen Einstellungs-Test brauchen.", "Online kommt eine weitere Variable hinzu. „Breitband“ beschreibt nicht Ping, Jitter, Paketverlust oder WLAN-Störungen. Wenn Kämpfe verzögert wirken, trenne lokale Bildrate von einem Netzwerkproblem, bevor du Hardware kaufst.", "Community-Berichte sind Beispiele, keine Garantie. Vergleiche CPU, GPU, RAM, Auflösung, Treiber und Einstellungen mit deinem PC. Miss Temperatur und Frame-Pacing in einem risikoarmen Test und entscheide mit eigenen Daten."],
            "image3_alt": "Offizieller Mistfall-Hunter-Steam-Screenshot mit einem Jäger an einer Truhe in einer dunklen Steinkammer", "image3_caption": "Offizieller Steam-Screenshot als visueller Kontext, nicht als Benchmark.",
            "check_title": "Fünf-Minuten-Check vor der Installation", "check": ["1. Lies Edition, CPU, RAM und GPU exakt aus Windows aus. 2. Vergleiche jede Zeile mit der offiziellen Tabelle. 3. Bestätige 45 GB freien Platz und nutze möglichst eine SSD mit Reserve. 4. Aktualisiere Windows und Grafiktreiber und schließe unnötige Overlays. 5. Teste nahe am Minimum eine kurze, risikoarme Runde und beobachte Stabilität und Temperaturen.", "Verwechsle die Store-Anforderungen nicht mit einem Versprechen zum Herunterladen. Steam ist die Quelle für Paket, Preis, Plattform und aktuellen Text. Diese Seite verlinkt dorthin und bietet keine Mirrors, Keys, Installer oder Sicherheitsprüfung. Ändern sich Zahlen, gilt die Live-Seite vor einem alten Artikel.", "Die sinnvolle Frage lautet nicht nur „startet es?“. Prüfe, ob das Spiel startet, in deinen Kämpfen ausreichend stabil bleibt und noch Raum für Extraktionsentscheidungen lässt. Bei Unsicherheit teste mit einer sicheren Klasse, wenig Ausrüstung und Notizen zu jeder Änderung."],
            "faq_title": "Häufige Fragen zu den Mistfall-Hunter-Systemanforderungen", "faq": [["Was sind die minimalen Anforderungen?", "Steam nennt Windows 10 64 Bit, i7-4770 oder Ryzen 5 1400, 12 GB RAM, GTX 1060 oder RX 580, DirectX 12, Breitband und 45 GB freien Platz. Eine SSD wird stark empfohlen."], ["Was sind die empfohlenen Specs?", "Empfohlen werden i7-9700 oder Ryzen 5 3600, 16 GB RAM, RTX 2070 oder RX 5700 XT, DirectX 12, Breitband und 45 GB. Die SSD-Empfehlung bleibt bestehen."], ["Kann ich mit 12 GB RAM spielen?", "Das erfüllt die offizielle Mindestzeile. Schließe Hintergrundprogramme und teste; die Mindestangabe garantiert keine FPS."], ["Braucht Mistfall Hunter eine SSD?", "Steam empfiehlt sie stark für eine bessere Erfahrung. Sie hilft beim Laden, ersetzt aber keine fehlende CPU- oder GPU-Leistung."], ["Wie viel Speicher wird benötigt?", "Die aktuelle Fassung nennt 45 GB freien Speicher. Lass Reserve für Patches, Caches und Windows."], ["Garantieren die Werte 60 FPS?", "Nein. Steam verknüpft die Zeilen nicht mit FPS, Auflösung oder Preset; teste dein System selbst."]],
            "source_title": "Offizielle Prüfquelle", "source_desc": "Offizielle Steam-Seite mit Anforderungen, Plattform, Preis, Reviews und Screenshots.", "related_title": "Verwandte Mistfall-Hunter-Ressourcen",
        },
        "ja": {
            "title": "Mistfall Hunter 必要スペック: PCで動くか確認",
            "description": "Mistfall Hunterの公式Steam最低・推奨動作環境、容量、SSDの注意点、購入前の確認手順をまとめます。",
            "h1": "Mistfall Hunter 必要スペック: 最低動作環境と推奨PC",
            "kicker": "動作環境ガイド | Steam公式確認日: 2026年9月24日",
            "quick_title": "先に結論: 公式の最低・推奨欄を比較する",
            "quick": ["Steam公式ページの現在の最低動作環境は、Windows 10 64 bit、12 GB RAM、GTX 1060またはRadeon RX 580、DirectX 12、ブロードバンド回線、45 GBの空き容量です。推奨欄では16 GB RAMとRTX 2070またはRadeon RX 5700 XTが指定されています。どちらもSSDが強く推奨されています。", "この数値は起動や互換性の目安であり、特定の解像度やフレームレートを保証するものではありません。ドライバー、温度、バックグラウンドアプリ、ノートPCの電力制限、画質設定、将来のパッチによって実際の結果は変わります。", "購入前は自分のCPU、GPU、メモリ、OS、空き容量を表と照合し、最後にSteam公式ページの最新表示を確認してください。このファンサイトはファイルを配布せず、未検証のPCを動作保証しません。"],
            "image1_alt": "雪原を進むハンターが描かれたMistfall Hunter公式Steamアート", "image1_caption": "このガイドが扱うゲームを確認するためのSteam公式アートです。性能測定ではありません。",
            "table_title": "Mistfall Hunter公式PC動作環境", "table_headers": ["項目", "最低", "推奨", "見方"],
            "table_rows": [["OS", "Windows 10 64 bit", "Windows 10 64 bit", "両方とも64 bit環境が必要です。"], ["CPU", "Intel Core i7-4770 / AMD Ryzen 5 1400", "Intel Core i7-9700 / AMD Ryzen 5 3600", "ブランドではなく型番を比較します。"], ["メモリ", "12 GB RAM", "16 GB RAM", "Windows、ブラウザ、ボイスチャット分を残します。"], ["GPU", "NVIDIA GTX 1060 / AMD RX 580", "NVIDIA RTX 2070 / AMD RX 5700 XT", "VRAM、ドライバー、ノートPCの電力も影響します。"], ["DirectX", "Version 12", "Version 12", "試す前にWindowsとGPUドライバーを更新します。"], ["回線", "ブロードバンド", "ブロードバンド", "速度の固定値はなく、遅延や安定性も重要です。"], ["容量", "45 GB空き", "45 GB空き", "アップデート用の余裕は別に必要です。"], ["追加", "SSD強く推奨", "SSD強く推奨", "ロードを助けますが弱いGPUの代わりにはなりません。"]],
            "compare_title": "自分のPCを正しく照合する方法", "compare": ["まずGPUの型番を確認します。Windowsのタスクマネージャーやメーカーの管理画面で、デスクトップ版かノート版かも見てください。「RTX」や「Radeon」だけでは不十分です。同じシリーズでもVRAM、冷却、電力制限が違うため、ノート版をデスクトップ版と同じ性能だと考えないでください。", "次にCPUとメモリを確認します。GPUだけが条件を満たしていても、CPU負荷の高い場面や複数アプリ起動中は余裕がなくなることがあります。12 GBは公式の最低値なので、ブラウザ、Discord、録画ソフトを同時に使うなら16 GBの方が扱いやすいです。", "最後にOSとストレージを見ます。45 GBぴったりではなく、パッチ、シェーダーキャッシュ、Windows更新のための余白を残してください。SSDはロードを短くする助けになりますが、最低値を下回るCPUやGPUを推奨構成に変えるものではありません。"],
            "image2_alt": "光る木を見上げるハンターが写るMistfall Hunter公式Steamスクリーンショット", "image2_caption": "Steam公式ストアのスクリーンショットです。描画対象の雰囲気を示しますが、FPSや設定は示しません。",
            "limits_title": "動作環境の数字だけでは分からないこと", "limits": ["Steamには目標FPS、解像度、プリセット、レイトレーシング、VRAMの指定がありません。混雑した脱出、ボス戦、パッチ後の性能も説明されていません。最低欄を満たしていても、重要なプレイ前に設定を試す必要があります。", "オンラインでは回線も変数です。「ブロードバンド」だけではping、jitter、パケットロス、Wi-Fi干渉を判断できません。操作が遅れて感じるときは、ハードウェアを買い替える前に描画の問題とネットワークの問題を分けて確認します。", "コミュニティの報告は参考例であり保証ではありません。CPU、GPU、RAM、解像度、ドライバー、設定が自分のPCと一致する報告だけを比較し、低リスクのテストで温度とフレームの安定性を記録してください。"],
            "image3_alt": "暗い石造りの部屋で宝箱へ向かうハンターのMistfall Hunter公式Steamスクリーンショット", "image3_caption": "描画負荷の文脈を示す公式スクリーンショットで、ベンチマークではありません。",
            "check_title": "インストール前の5分チェック", "check": ["1. WindowsでOS、CPU、RAM、GPUの正確な型番を確認します。2. 表の各行と照合します。3. 45 GB以上を確保し、可能なら余裕のあるSSDに入れます。4. WindowsとGPUドライバーを更新し、不要なオーバーレイを閉じます。5. 最低構成に近い場合は、装備を失っても困らない短いテストで温度と安定性を見ます。", "公式要件をダウンロードの約束と混同しないでください。価格、プラットフォーム、パッケージ、最新要件はSteam公式が基準です。このサイトはSteamへ案内するだけで、ミラー、キー、インストーラー、安全スキャンを提供しません。数字が変わったら古い記事より公式ページを優先します。", "「起動するか」だけではなく、戦闘中に十分安定するか、脱出の判断に集中できるかを考えます。迷う場合は安全寄りのクラスと少ない装備で試し、設定を一つずつ変えて結果をメモしてください。"],
            "faq_title": "Mistfall Hunter必要スペック よくある質問", "faq": [["最低動作環境は？", "Steam公式はWindows 10 64 bit、i7-4770またはRyzen 5 1400、12 GB RAM、GTX 1060またはRX 580、DirectX 12、ブロードバンド、45 GB空きを示しています。SSDも強く推奨です。"], ["推奨スペックは？", "i7-9700またはRyzen 5 3600、16 GB RAM、RTX 2070またはRX 5700 XT、DirectX 12、ブロードバンド、45 GB空きです。SSDの注意も同じです。"], ["12 GB RAMで遊べますか？", "公式最低欄には合致します。不要なアプリを閉じて自分のPCで確認してください。最低値はFPS保証ではありません。"], ["SSDは必須ですか？", "Steamは快適性のため強く推奨しています。ロードには有効ですが、CPUやGPU不足を補うものではありません。"], ["必要な容量は？", "現在の公式欄は45 GBの空き容量です。アップデート、キャッシュ、Windows用に追加の余裕を残してください。"], ["60 FPSが保証されますか？", "保証されません。FPS、解像度、プリセットは指定されていないため、自分の環境で試す必要があります。"]],
            "source_title": "公式確認ソース", "source_desc": "動作環境、プラットフォーム、価格、レビュー、画像を掲載するSteam公式ページです。", "related_title": "関連するMistfall Hunterガイド",
        },
        "pt": {
            "title": "Requisitos de sistema de Mistfall Hunter: seu PC roda?",
            "description": "Veja os requisitos mínimos e recomendados oficiais de Mistfall Hunter, espaço, nota sobre SSD e um checklist antes de comprar.",
            "h1": "Requisitos de sistema de Mistfall Hunter: PC mínimo e recomendado",
            "kicker": "Guia de requisitos | Verificação oficial do Steam: 24 de setembro de 2026",
            "quick_title": "Resposta rápida: comece pelas linhas oficiais",
            "quick": ["A página oficial do Steam informa Windows 10 64 bits, 12 GB de RAM, GTX 1060 ou Radeon RX 580, DirectX 12, internet banda larga e 45 GB livres como mínimo. A linha recomendada sobe para 16 GB de RAM e RTX 2070 ou Radeon RX 5700 XT. As duas linhas recomendam SSD.", "Esses números ajudam a avaliar compatibilidade, mas não prometem FPS fixo. Requisito mínimo é uma referência da loja, não garantia de fluidez em uma resolução específica. Drivers, temperatura, programas abertos, limite de energia do notebook, configurações e patches alteram o resultado.", "Use a página como checklist antes de comprar ou instalar. Compare CPU, GPU, memória, Windows e espaço livre reais com a tabela, depois confira o texto atual na página oficial do Steam. Este site fan-made não distribui arquivos nem certifica um PC que não foi testado."],
            "image1_alt": "Arte oficial do Steam de Mistfall Hunter com caçadores em um campo nevado", "image1_caption": "Arte oficial do Steam para identificar o jogo deste guia. Não é um benchmark.",
            "table_title": "Requisitos oficiais de PC de Mistfall Hunter", "table_headers": ["Componente", "Mínimo", "Recomendado", "Como interpretar"],
            "table_rows": [["Sistema", "Windows 10 64 bits", "Windows 10 64 bits", "As duas linhas exigem instalação de 64 bits."], ["Processador", "Intel Core i7-4770 / AMD Ryzen 5 1400", "Intel Core i7-9700 / AMD Ryzen 5 3600", "Compare o modelo exato, não apenas a marca."], ["Memória", "12 GB RAM", "16 GB RAM", "Deixe margem para Windows, navegador e voz."], ["Gráficos", "NVIDIA GTX 1060 / AMD RX 580", "NVIDIA RTX 2070 / AMD RX 5700 XT", "VRAM, drivers e limite do notebook também importam."], ["DirectX", "Versão 12", "Versão 12", "Atualize Windows e driver antes do teste."], ["Rede", "Internet banda larga", "Internet banda larga", "A ficha não fixa velocidade; estabilidade também importa."], ["Armazenamento", "45 GB livres", "45 GB livres", "Espaço livre não é orçamento permanente de patches."], ["Nota", "SSD fortemente recomendado", "SSD fortemente recomendado", "SSD ajuda no carregamento, não substitui GPU fraca."]],
            "compare_title": "Como comparar seu PC sem chute", "compare": ["Comece pela placa de vídeo, pois a diferença entre mínimo e recomendado é grande. Veja o modelo exato no Gerenciador de Tarefas ou no painel do fabricante. “RTX” ou “Radeon” sozinho não basta: memória, refrigeração e potência variam, especialmente entre versões de desktop e notebook.", "Depois confira processador e RAM. Um PC pode atingir a linha da GPU e ainda ficar limitado em cenas pesadas para a CPU ou com vários programas abertos. Doze gigabytes é a base da loja; se Windows, navegador, Discord, gravação ou overlays já usam memória, 16 GB dão mais folga.", "Por fim, confirme Windows e disco. Deixe mais de 45 GB quando o drive estiver cheio, porque patches, caches e atualizações também precisam de espaço. SSD pode melhorar carregamentos, mas não transforma CPU ou GPU abaixo do mínimo em configuração recomendada."],
            "image2_alt": "Captura oficial do Steam de Mistfall Hunter com um caçador diante de uma árvore luminosa", "image2_caption": "Captura oficial da loja Steam. Mostra um ambiente para renderizar, mas não fixa FPS ou configurações.",
            "limits_title": "O que os requisitos não informam", "limits": ["O Steam não informa FPS alvo, resolução, preset, ray tracing ou recomendação de VRAM. Também não descreve uma extração movimentada, uma luta contra chefe ou o desempenho depois de um patch. Um PC acima do mínimo ainda pode precisar de ajuste.", "A rede é outra variável. “Banda larga” não resume ping, jitter, perda de pacotes ou interferência Wi-Fi. Se o combate atrasar, separe um problema de frames local de um problema de rede antes de trocar hardware.", "Relatos da comunidade são exemplos, não garantia. Compare CPU, GPU, RAM, resolução, drivers e configurações do relato com seu PC. Faça um teste de baixo risco, observe temperatura e estabilidade e decida com seus próprios dados."],
            "image3_alt": "Captura oficial do Steam de Mistfall Hunter com um caçador perto de um baú em uma câmara escura", "image3_caption": "Captura oficial do Steam usada como contexto visual, não como benchmark.",
            "check_title": "Checklist de cinco minutos antes de instalar", "check": ["1. Leia no Windows a edição, CPU, RAM e GPU exatas. 2. Compare cada linha com a tabela oficial. 3. Confirme 45 GB livres e prefira SSD com espaço adicional. 4. Atualize Windows e driver e feche overlays desnecessários. 5. Se estiver perto do mínimo, faça uma partida curta e de baixo risco para observar estabilidade e temperaturas.", "Não confunda os requisitos da loja com promessa de instalação. O Steam é a fonte para pacote, preço, plataforma e texto atual. Este site aponta para lá e não oferece mirror, chave, instalador ou varredura de segurança. Se os números mudarem, a página oficial vale mais que um guia antigo.", "A pergunta útil não é somente “abre?”. Veja se o jogo abre, mantém estabilidade suficiente para seus combates e deixa margem para decisões de extração. Em dúvida, teste com uma classe segura, pouco equipamento e anote cada mudança de configuração."],
            "faq_title": "Perguntas frequentes sobre os requisitos de Mistfall Hunter", "faq": [["Quais são os requisitos mínimos?", "O Steam informa Windows 10 64 bits, i7-4770 ou Ryzen 5 1400, 12 GB RAM, GTX 1060 ou RX 580, DirectX 12, banda larga e 45 GB livres. SSD é fortemente recomendado."], ["Quais são os recomendados?", "A linha recomendada usa i7-9700 ou Ryzen 5 3600, 16 GB RAM, RTX 2070 ou RX 5700 XT, DirectX 12, banda larga e 45 GB. SSD continua recomendado."], ["Dá para jogar com 12 GB de RAM?", "Isso atende ao mínimo oficial. Feche programas e teste seu PC; o mínimo não fixa FPS."], ["Mistfall Hunter exige SSD?", "O Steam recomenda muito o SSD para uma experiência melhor. Ele ajuda nos carregamentos, mas não substitui CPU ou GPU suficiente."], ["Quanto espaço é necessário?", "A ficha atual diz 45 GB livres. Deixe margem para patches, caches e Windows."], ["Os requisitos garantem 60 FPS?", "Não. FPS, resolução e preset não são informados; verifique seu próprio ambiente."]],
            "source_title": "Fonte oficial de verificação", "source_desc": "Página oficial do Steam com requisitos, plataforma, preço, avaliações e imagens.", "related_title": "Guias relacionados de Mistfall Hunter",
        },
        "ko": {
            "title": "Mistfall Hunter 시스템 요구 사항: PC에서 실행될까?",
            "description": "Mistfall Hunter 공식 Steam 최소·권장 PC 사양, 저장 공간, SSD 권장 이유와 구매 전 점검 방법을 확인하세요.",
            "h1": "Mistfall Hunter 시스템 요구 사항: 최소 및 권장 PC 사양",
            "kicker": "사양 가이드 | Steam 공식 확인일: 2026년 9월 24일",
            "quick_title": "빠른 결론: 공식 표부터 비교하세요",
            "quick": ["Steam 공식 페이지의 현재 최소 사양은 Windows 10 64비트, 12GB RAM, GTX 1060 또는 Radeon RX 580, DirectX 12, 광대역 인터넷, 45GB 여유 공간입니다. 권장 사양은 16GB RAM과 RTX 2070 또는 Radeon RX 5700 XT로 올라갑니다. 두 항목 모두 SSD 설치를 강하게 권장합니다.", "이 수치는 호환성 기준이지 특정 해상도나 프레임을 보장하지 않습니다. 최소 사양을 만족해도 드라이버, 온도, 백그라운드 프로그램, 노트북 전력 제한, 그래픽 설정, 패치에 따라 실제 결과가 달라질 수 있습니다.", "구매 전 CPU, GPU, 메모리, 운영체제, 여유 공간을 표와 대조하고 Steam 공식 페이지에서 최신 문구를 다시 확인하세요. 이 팬 사이트는 파일을 제공하지 않으며 테스트하지 않은 PC의 실행을 보증하지 않습니다."],
            "image1_alt": "눈 덮인 전장에서 사냥꾼들이 움직이는 Mistfall Hunter 공식 Steam 아트", "image1_caption": "이 가이드의 게임을 확인하기 위한 Steam 공식 아트입니다. 성능 벤치마크는 아닙니다.",
            "table_title": "Mistfall Hunter 공식 PC 요구 사항", "table_headers": ["항목", "최소", "권장", "확인 방법"],
            "table_rows": [["운영체제", "Windows 10 64비트", "Windows 10 64비트", "두 항목 모두 64비트 설치가 필요합니다."], ["프로세서", "Intel Core i7-4770 / AMD Ryzen 5 1400", "Intel Core i7-9700 / AMD Ryzen 5 3600", "브랜드가 아니라 정확한 모델을 비교합니다."], ["메모리", "12GB RAM", "16GB RAM", "Windows, 브라우저, 음성 채팅 공간을 남기세요."], ["그래픽", "NVIDIA GTX 1060 / AMD RX 580", "NVIDIA RTX 2070 / AMD RX 5700 XT", "VRAM, 드라이버, 노트북 전력도 영향을 줍니다."], ["DirectX", "버전 12", "버전 12", "테스트 전에 Windows와 드라이버를 업데이트하세요."], ["네트워크", "광대역 인터넷", "광대역 인터넷", "고정 속도는 없으며 안정성도 중요합니다."], ["저장 공간", "45GB 여유", "45GB 여유", "패치용 공간은 별도로 남겨야 합니다."], ["추가", "SSD 강력 권장", "SSD 강력 권장", "SSD는 로딩을 돕지만 약한 GPU를 대체하지 않습니다."]],
            "compare_title": "내 PC를 추측 없이 비교하는 법", "compare": ["먼저 그래픽카드의 정확한 모델을 확인하세요. 작업 관리자나 제조사 도구에서 데스크톱용인지 노트북용인지도 봅니다. RTX나 Radeon이라는 이름만으로는 부족합니다. 같은 제품군이라도 VRAM, 냉각, 전력 제한이 다르므로 노트북 버전을 데스크톱 버전과 같다고 보면 안 됩니다.", "다음으로 CPU와 메모리를 확인합니다. GPU가 조건을 충족해도 CPU 부하가 큰 장면이나 여러 프로그램을 켠 상태에서는 여유가 부족할 수 있습니다. 12GB는 공식 최소치이므로 브라우저, Discord, 녹화 프로그램, 오버레이를 함께 사용한다면 16GB가 더 편합니다.", "마지막으로 운영체제와 디스크를 확인하세요. 45GB만 딱 남기지 말고 패치, 셰이더 캐시, Windows 업데이트용 공간을 두세요. SSD는 로딩을 줄이는 데 도움을 주지만 최소 기준보다 낮은 CPU나 GPU를 권장 사양으로 바꾸지는 않습니다."],
            "image2_alt": "빛나는 나무 앞에 선 사냥꾼이 보이는 Mistfall Hunter 공식 Steam 스크린샷", "image2_caption": "Steam 공식 스크린샷입니다. 렌더링할 환경을 보여주지만 FPS나 설정을 확정하지는 않습니다.",
            "limits_title": "요구 사항만으로 알 수 없는 것", "limits": ["Steam은 목표 FPS, 해상도, 프리셋, 레이트레이싱, VRAM 권장치를 공개하지 않습니다. 혼잡한 탈출, 보스 전투, 패치 이후 성능도 설명하지 않습니다. 최소 사양을 넘겨도 중요한 플레이 전에는 설정을 테스트해야 합니다.", "온라인에서는 네트워크도 변수입니다. 광대역이라는 말만으로 ping, jitter, 패킷 손실, Wi-Fi 간섭을 알 수 없습니다. 전투가 늦게 반응하면 하드웨어를 바꾸기 전에 프레임 문제와 네트워크 문제를 나눠 확인하세요.", "커뮤니티 성능 보고서는 참고 사례일 뿐 보장이 아닙니다. CPU, GPU, RAM, 해상도, 드라이버, 설정이 같은지 비교하고 위험이 낮은 테스트에서 온도와 프레임 안정성을 기록하세요."],
            "image3_alt": "어두운 석실에서 상자에 다가가는 사냥꾼이 보이는 Mistfall Hunter 공식 Steam 스크린샷", "image3_caption": "렌더링 부하의 맥락을 보여주는 공식 스크린샷이며 벤치마크가 아닙니다.",
            "check_title": "설치 전 5분 점검", "check": ["1. Windows에서 OS, CPU, RAM, GPU의 정확한 모델을 확인합니다. 2. 공식 표의 각 줄과 비교합니다. 3. 45GB 이상을 확보하고 가능하면 여유 있는 SSD를 사용합니다. 4. Windows와 그래픽 드라이버를 업데이트하고 불필요한 오버레이를 닫습니다. 5. 최소 사양에 가까우면 잃어도 괜찮은 장비로 짧게 테스트하며 온도와 안정성을 확인합니다.", "공식 요구 사항을 다운로드 약속으로 오해하지 마세요. 패키지, 가격, 플랫폼, 최신 사양은 Steam 공식 페이지가 기준입니다. 이 사이트는 Steam으로 연결할 뿐 미러, 키, 설치 파일, 보안 검사를 제공하지 않습니다. 숫자가 바뀌면 오래된 글보다 공식 페이지를 우선하세요.", "‘실행되는가’만 묻지 말고 전투에서 충분히 안정적인지, 탈출 판단에 집중할 여유가 있는지 확인하세요. 확신이 없으면 안전한 클래스와 적은 장비로 테스트하고 설정을 하나씩 바꿔 기록하세요."],
            "faq_title": "Mistfall Hunter 시스템 요구 사항 자주 묻는 질문", "faq": [["최소 사양은 무엇인가요?", "Steam은 Windows 10 64비트, i7-4770 또는 Ryzen 5 1400, 12GB RAM, GTX 1060 또는 RX 580, DirectX 12, 광대역, 45GB 여유를 제시합니다. SSD도 강력 권장입니다."], ["권장 사양은 무엇인가요?", "i7-9700 또는 Ryzen 5 3600, 16GB RAM, RTX 2070 또는 RX 5700 XT, DirectX 12, 광대역, 45GB 여유입니다. SSD 권장도 같습니다."], ["12GB RAM으로 플레이할 수 있나요?", "공식 최소 항목에는 해당합니다. 불필요한 앱을 닫고 직접 테스트하세요. 최소 사양은 FPS를 보장하지 않습니다."], ["SSD가 필수인가요?", "Steam은 더 나은 경험을 위해 강하게 권장합니다. 로딩에는 도움이 되지만 부족한 CPU나 GPU를 대신하지는 않습니다."], ["저장 공간은 얼마나 필요한가요?", "현재 공식 표는 45GB 여유입니다. 패치, 캐시, Windows를 위해 추가 공간을 남기세요."], ["60 FPS가 보장되나요?", "아닙니다. FPS, 해상도, 프리셋이 지정되지 않았으므로 자신의 환경에서 확인해야 합니다."]],
            "source_title": "공식 확인 출처", "source_desc": "요구 사항, 플랫폼, 가격, 리뷰, 스크린샷을 제공하는 Steam 공식 페이지입니다.", "related_title": "관련 Mistfall Hunter 가이드",
        },
        "it": {
            "title": "Requisiti di sistema Mistfall Hunter: il tuo PC lo regge?",
            "description": "Controlla i requisiti PC minimi e consigliati ufficiali di Mistfall Hunter, spazio, nota SSD e verifiche pratiche prima dell acquisto.",
            "h1": "Requisiti di sistema Mistfall Hunter: PC minimo e consigliato",
            "kicker": "Requisiti | Verifica ufficiale Steam: 24 settembre 2026",
            "quick_title": "Risposta rapida: parti dalle righe ufficiali",
            "quick": ["La pagina Steam ufficiale indica Windows 10 64 bit, 12 GB di RAM, GTX 1060 o Radeon RX 580, DirectX 12, connessione broadband e 45 GB liberi come minimo. La riga consigliata sale a 16 GB di RAM e RTX 2070 o Radeon RX 5700 XT. Entrambe consigliano un SSD.", "Questi valori aiutano a capire la compatibilità, ma non garantiscono FPS fissi. Il minimo è una base dello store, non una promessa a una certa risoluzione. Driver, temperature, programmi aperti, limiti del portatile, impostazioni e patch cambiano il risultato.", "Usa la pagina come checklist prima di comprare o installare. Confronta CPU, GPU, memoria, sistema operativo e spazio reale con la tabella, poi controlla il testo aggiornato su Steam. Questo sito fan-made non distribuisce file e non certifica PC non testati."],
            "image1_alt": "Artwork ufficiale Steam di Mistfall Hunter con cacciatori su un campo innevato", "image1_caption": "Artwork ufficiale Steam per identificare il gioco della guida. Non è un benchmark.",
            "table_title": "Requisiti PC ufficiali di Mistfall Hunter", "table_headers": ["Componente", "Minimo", "Consigliato", "Come leggerlo"],
            "table_rows": [["Sistema operativo", "Windows 10 64 bit", "Windows 10 64 bit", "Entrambe le righe richiedono un sistema a 64 bit."], ["Processore", "Intel Core i7-4770 / AMD Ryzen 5 1400", "Intel Core i7-9700 / AMD Ryzen 5 3600", "Confronta il modello esatto, non solo la marca."], ["Memoria", "12 GB RAM", "16 GB RAM", "Lascia margine per Windows, browser e voce."], ["Grafica", "NVIDIA GTX 1060 / AMD RX 580", "NVIDIA RTX 2070 / AMD RX 5700 XT", "Contano anche VRAM, driver e potenza del portatile."], ["DirectX", "Versione 12", "Versione 12", "Aggiorna Windows e driver prima del test."], ["Rete", "Internet broadband", "Internet broadband", "La scheda non fissa una velocità; conta la stabilità."], ["Spazio", "45 GB liberi", "45 GB liberi", "Lo spazio libero non è un budget permanente per patch."], ["Nota", "SSD fortemente consigliato", "SSD fortemente consigliato", "L SSD aiuta i caricamenti, non sostituisce una GPU debole."]],
            "compare_title": "Come confrontare il PC senza indovinare", "compare": ["Inizia dalla scheda video perché il salto tra minimo e consigliato è importante. Leggi il modello esatto nel Task Manager o nel pannello del produttore. “RTX” o “Radeon” non basta: memoria, raffreddamento e potenza cambiano, soprattutto tra desktop e portatile.", "Poi controlla CPU e RAM. Un PC può rispettare la riga GPU e restare limitato in scene pesanti per la CPU o con molti programmi aperti. Dodici gigabyte è la base Steam; se Windows, browser, Discord, registrazione o overlay usano già memoria, 16 GB offrono più margine.", "Infine verifica sistema e disco. Lascia più di 45 GB se l unità è quasi piena, perché patch, cache e Windows richiedono spazio. Un SSD può ridurre i caricamenti, ma non trasforma CPU o GPU sotto il minimo in una configurazione consigliata."],
            "image2_alt": "Screenshot ufficiale Steam di Mistfall Hunter con un cacciatore davanti a un albero luminoso", "image2_caption": "Screenshot ufficiale dello store Steam. Mostra un ambiente da renderizzare, ma non fissa FPS o impostazioni.",
            "limits_title": "Cosa non dicono i requisiti", "limits": ["Steam non indica FPS target, risoluzione, preset, ray tracing o VRAM. Non descrive una sessione affollata, un boss o il rendimento dopo una patch. Anche un PC sopra il minimo può quindi richiedere un test delle impostazioni.", "La rete è un altra variabile. “Broadband” non descrive ping, jitter, perdita di pacchetti o interferenze Wi-Fi. Se il combattimento sembra in ritardo, separa un problema locale di frame da uno di rete prima di cambiare hardware.", "I report della community sono esempi, non garanzie. Confronta CPU, GPU, RAM, risoluzione, driver e impostazioni con il tuo PC. Misura temperature e stabilità in un test a basso rischio e decidi con i tuoi dati."],
            "image3_alt": "Screenshot ufficiale Steam di Mistfall Hunter con un cacciatore vicino a un forziere in una sala buia", "image3_caption": "Screenshot ufficiale Steam usato come contesto visivo, non come benchmark.",
            "check_title": "Controllo di cinque minuti prima dell installazione", "check": ["1. Leggi in Windows edizione, CPU, RAM e GPU esatte. 2. Confronta ogni riga con la tabella ufficiale. 3. Conferma 45 GB liberi e preferisci un SSD con spazio extra. 4. Aggiorna Windows e driver e chiudi gli overlay inutili. 5. Se sei vicino al minimo, fai una partita breve e a basso rischio per osservare stabilità e temperature.", "Non confondere i requisiti dello store con una promessa di installazione. Steam è la fonte per pacchetto, prezzo, piattaforma e testo attuale. Questo sito rimanda lì e non offre mirror, chiavi, installer o scansioni di sicurezza. Se i numeri cambiano, vale la pagina ufficiale più di una guida vecchia.", "La domanda utile non è solo «si avvia?». Verifica se resta abbastanza stabile nei combattimenti e lascia margine alle decisioni di estrazione. Se hai dubbi, prova con una classe sicura, poco equipaggiamento e note per ogni modifica."],
            "faq_title": "Domande frequenti sui requisiti di sistema di Mistfall Hunter", "faq": [["Quali sono i requisiti minimi?", "Steam indica Windows 10 64 bit, i7-4770 o Ryzen 5 1400, 12 GB RAM, GTX 1060 o RX 580, DirectX 12, broadband e 45 GB liberi. L SSD è fortemente consigliato."], ["Quali sono i requisiti consigliati?", "La riga consigliata usa i7-9700 o Ryzen 5 3600, 16 GB RAM, RTX 2070 o RX 5700 XT, DirectX 12, broadband e 45 GB. Anche qui l SSD è consigliato."], ["Posso giocare con 12 GB di RAM?", "Rientri nel minimo ufficiale. Chiudi i programmi e prova il tuo PC; il minimo non fissa gli FPS."], ["Serve un SSD?", "Steam lo consiglia molto per una migliore esperienza. Aiuta i caricamenti, ma non sostituisce CPU o GPU sufficienti."], ["Quanto spazio serve?", "La scheda attuale indica 45 GB liberi. Lascia margine per patch, cache e Windows."], ["I requisiti garantiscono 60 FPS?", "No. FPS, risoluzione e preset non sono indicati; verifica il tuo ambiente."]],
            "source_title": "Fonte ufficiale", "source_desc": "Pagina Steam ufficiale con requisiti, piattaforma, prezzo, recensioni e immagini.", "related_title": "Risorse Mistfall Hunter correlate",
        },
    }
    for locale, copy in localized.items():
        english = SYSTEM_REQUIREMENTS_PAGE_DATA["en"]
        source_link_labels = {
            "en": "Mistfall Hunter on Steam",
            "es": "Mistfall Hunter en Steam",
            "ja": "Mistfall Hunter（Steam公式）",
            "fr": "Mistfall Hunter sur Steam",
            "de": "Mistfall Hunter auf Steam",
            "pt": "Mistfall Hunter no Steam",
            "ko": "Steam의 Mistfall Hunter 공식 페이지",
            "it": "Mistfall Hunter su Steam",
        }
        sections = [
            {"type": "rich", "title": copy["quick_title"], "paragraphs": copy["quick"]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": copy["image1_alt"], "caption": copy["image1_caption"], "width": 1280, "height": 360},
            {"type": "table", "title": copy["table_title"], "headers": copy["table_headers"], "rows": copy["table_rows"]},
            {"type": "rich", "title": copy["compare_title"], "paragraphs": copy["compare"]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-system-requirements-pc.webp", "alt": copy["image2_alt"], "caption": copy["image2_caption"], "width": 960, "height": 540},
            {"type": "rich", "title": copy["limits_title"], "paragraphs": copy["limits"]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-system-requirements-combat.webp", "alt": copy["image3_alt"], "caption": copy["image3_caption"], "width": 960, "height": 540},
            {"type": "rich", "title": copy["check_title"], "paragraphs": copy["check"]},
            {"type": "faq", "title": copy["faq_title"], "items": copy["faq"]},
            {"type": "links", "title": copy["source_title"], "items": [[source_link_labels[locale], "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", copy["source_desc"], "noopener"]]},
        ]
        data[locale] = _clone_with_locale(locale, {"title": copy["title"], "description": copy["description"], "h1": copy["h1"], "kicker": copy["kicker"]}, sections)
    return data


SYSTEM_REQUIREMENTS_PAGE_DATA = build_system_requirements_page_data()
