TIER_LIST_PAGE_DATA = {
    "en": {
        "page": {
            "title": "Mistfall Hunter Tier List: Best Classes by Mode",
            "description": "A practical Mistfall Hunter tier list for solo, duo, and squad play, with class tradeoffs, beginner picks, and a clear non-official ranking method.",
            "h1": "Mistfall Hunter Tier List: Best Classes for Solo, Duo, and Squad",
            "kicker": "Mistfall Hunter class tier list | Updated August 2026",
        },
        "sections": [
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": "Official Steam artwork for Mistfall Hunter showing hunters in a snowy battlefield", "caption": "Official Steam artwork used to identify the game. It is not evidence of class balance or a gameplay capture."},
            {"type": "rich", "title": "Quick verdict: the best class depends on the run", "paragraphs": [
                "If you need one safe starting point, Mercenary is the most forgiving solo pick in this fan-made Mistfall Hunter tier list. It offers clear frontline pressure and gives a new player more room to recover after a bad trade. Withered Knight is the stronger anchor when a squad needs someone to hold space, while Seer rises when information and safer calls matter more than raw damage.",
                "Shadowstrix and Sorcerer belong near the top of a burst-focused list, but they are not automatic winners. Both ask for cleaner timing, better positioning, and a willingness to accept more punishment when an engagement goes wrong. Blackarrow sits between safety and pressure: its range and scouting value are useful, but it still relies on choosing the right fight.",
                "This is a scenario tier list, not an official ranking and not a claim about a permanent meta. Mistfall Hunter is a live game with balance changes, different team habits, and a large skill gap between players. Read the table as a starting decision, then use the class guide and build planner to turn the recommendation into a run you can actually explain and repeat.",
            ]},
            {"type": "table", "title": "Mistfall Hunter tier list by mode", "headers": ["Class", "Solo", "Duo", "Squad", "Why it lands here"], "rows": [
                ["Mercenary", "S", "A", "A", "Forgiving frontline pressure and a simple recovery pattern."],
                ["Withered Knight", "A", "S", "S", "Durability, space control, and a reliable anchor for allies."],
                ["Seer", "B", "A", "S", "Information and utility become more valuable as coordination grows."],
                ["Blackarrow", "A", "A", "A", "Range and scouting give value when the player reads engagements well."],
                ["Shadowstrix", "A", "S", "B", "High burst and mobility reward timing but punish exposed exits."],
                ["Sorcerer", "B", "S", "S", "Area pressure is excellent in planned fights but less forgiving alone."],
            ]},
            {"type": "rich", "title": "How this class tier list is built", "paragraphs": [
                "The first dimension is failure tolerance. A class that keeps options open after a missed attack is easier to recommend to a new player than a class that needs a perfect opening. That is why Mercenary can outrank a flashier damage option in solo play even when the damage ceiling is lower.",
                "The second dimension is decision value. Tracking, space control, range, and reliable disengage can win an extraction without appearing in a damage screenshot. Seer and Withered Knight gain weight in duo and squad play because a teammate can act on the information or space they create.",
                "The third dimension is execution demand. Burst and mobility are valuable only when the player can start and end an engagement on purpose. Shadowstrix and Sorcerer therefore move up for experienced groups and down for a first run. The labels describe a use case, not a universal power measurement.",
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-modes.webp", "alt": "Editorial illustration of Mistfall Hunter hunters choosing three snowy extraction routes", "width": 1024, "height": 1024, "caption": "Editorial illustration for the mode comparison. It is a conceptual visual, not an official map or gameplay screenshot."},
            {"type": "rich", "title": "Class-by-class decision guide", "paragraphs": [
                "Choose Mercenary when your priority is learning the extraction loop without turning every mistake into a lost run. The class gives a readable frontline job: close distance, pressure one target, and leave before the fight becomes too expensive. It is also a good baseline for testing whether your problem is class choice or route discipline.",
                "Choose Withered Knight when your group needs an anchor rather than another damage dealer. Holding a doorway, buying time for a retreat, or protecting a fragile teammate can matter more than topping a damage chart. In duo play, that consistency gives the partner a clearer window to scout, burst, or finish a fight.",
                "Choose Seer or Blackarrow when information is the missing resource. Seer is the better fit for a coordinated squad that can respond to calls, while Blackarrow works for players who want distance and a measured pace. Neither class removes the need to read the map; both reward players who avoid low-value fights.",
                "Choose Shadowstrix or Sorcerer when the group already has a stable plan and you want to convert a clean opening into pressure. Shadowstrix favors flanks and fast disengage. Sorcerer favors zone control and grouped targets. If your team cannot describe who starts, who follows, and who leaves, their theoretical S-tier value is less important than a safer pick.",
            ]},
            {"type": "table", "title": "Fast picks for common situations", "headers": ["Situation", "Start with", "Reason"], "rows": [
                ["First solo extraction", "Mercenary", "The role is easy to read and mistakes are more recoverable."],
                ["Safe duo anchor", "Withered Knight", "Creates time and space for the second player."],
                ["Coordinated squad utility", "Seer", "Turns information into safer movement and target calls."],
                ["Ranged scouting", "Blackarrow", "Lets a patient player choose when to commit."],
                ["Aggressive duo burst", "Shadowstrix or Sorcerer", "Both can exploit a planned opening with higher execution demand."],
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-roles.webp", "alt": "Editorial illustration comparing a shielded frontline hunter, ranged scout, and shadow caster in a snowy Mistfall setting", "width": 1024, "height": 1024, "caption": "Conceptual role illustration showing survivability, information, and burst as different tradeoffs; it is not an official character reveal."},
            {"type": "rich", "title": "How to use the list after a patch", "paragraphs": [
                "Do not move a class between tiers because of one dramatic clip or one early match. First check whether the change affects damage, survivability, range, cooldowns, equipment access, or the way a class enters and exits a fight. A small number change can be less important than a new interaction that changes the whole decision pattern.",
                "Re-test the class in the mode where you intend to play it. A buff that makes solo clearing faster may not improve squad value, while a control or information change may matter most when teammates can coordinate around it. This is why the table separates solo, duo, and squad instead of publishing a single universal S tier.",
                "If two classes are close, choose the role your group lacks and record what happened. That feedback is more useful than chasing a ranking without context. We will update this page when verified patch notes or repeated, explainable gameplay evidence changes the recommendation boundary.",
            ]},
            {"type": "faq", "title": "Mistfall Hunter tier list FAQ", "items": [
                ["What is the best class in Mistfall Hunter?", "Mercenary is the safest general starting point for solo players, while Withered Knight and Seer are stronger recommendations when a squad needs an anchor or information. The best class still depends on mode, experience, and the role your team lacks."],
                ["What is the best solo class in Mistfall Hunter?", "Start with Mercenary if you want the most forgiving frontline plan. Blackarrow or Shadowstrix can be better when you already understand spacing, scouting, and disengage timing."],
                ["What is the Mistfall Hunter class tier list for duo play?", "Withered Knight, Shadowstrix, Sorcerer, and Seer all rise in duo play for different reasons. Pick the one that complements your partner: anchor, burst, zone pressure, or information."],
                ["Is this an official Mistfall Hunter tier list?", "No. It is an independent, fan-made comparison based on role clarity, failure tolerance, team utility, and execution demand. Check official notes and your current version before treating a ranking as final."],
                ["Should beginners follow the S tier only?", "No. A lower-risk A-tier class that you can explain and extract with is usually better than an S-tier class whose timing you do not understand. Use the table to narrow the test, not to skip the learning step."],
                ["Where can I compare the classes in more detail?", "Use the Mistfall Hunter classes guide for role profiles and the build planner for solo, duo, and squad recommendations. The gameplay guide adds the extraction-loop context behind these choices."],
            ]},
            {"type": "links", "title": "Official reference", "items": [["Mistfall Hunter on Steam", "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", "Official platform and product identity reference.", "noopener"]]},
            {"type": "related", "title": "Related Mistfall Hunter guides", "items": [["Mistfall Hunter classes guide", "/classes/", "Compare roles, risk, and beginner direction."], ["Mistfall Hunter build planner", "/build-planner/", "Match a class to solo, duo, or squad play."], ["Mistfall Hunter gameplay guide", "/gameplay/", "Understand the extraction loop behind the choices."], ["Mistfall Hunter review", "/review/", "Read the wider buyer and game-loop tradeoffs."]]},
        ],
    },
    "es": {
        "page": {"title": "Tier list de Mistfall Hunter: mejores clases", "description": "Tier list practica de Mistfall Hunter para solo, duo y escuadron, con riesgos, elecciones para principiantes y un metodo no oficial.", "h1": "Tier list de Mistfall Hunter: mejores clases para solo, duo y escuadron", "kicker": "Tier list de clases | Actualizada en agosto de 2026"},
        "sections": [
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": "Arte oficial de Steam de Mistfall Hunter con cazadores en un campo nevado", "caption": "Arte oficial de Steam para identificar el juego. No demuestra equilibrio de clases ni es una captura de partida."},
            {"type": "rich", "title": "Veredicto rapido: la mejor clase depende de la partida", "paragraphs": [
                "Si necesitas un comienzo seguro, Mercenary es la opcion mas permisiva para jugar solo en esta tier list fan-made de Mistfall Hunter. Su presion frontal es facil de leer y permite recuperarse mejor de un intercambio malo. Withered Knight funciona mejor como ancla de escuadron, mientras Seer gana valor cuando el equipo necesita informacion y decisiones mas seguras.",
                "Shadowstrix y Sorcerer suben en una lista centrada en burst, pero no son ganadores automaticos. Exigen mejor posicionamiento y timing, y castigan mas una entrada sin salida. Blackarrow queda en el centro: ofrece alcance y exploracion, pero depende de elegir bien cada combate.",
                "Esta es una comparacion por escenarios, no una tier list oficial ni una promesa de meta permanente. El juego puede cambiar con parches, habilidad y costumbres del equipo. Usa la tabla para elegir una prueba y despues combina la guia de clases con el planner para convertirla en una build repetible.",
            ]},
            {"type": "table", "title": "Tier list por modo", "headers": ["Clase", "Solo", "Duo", "Escuadron", "Por que"], "rows": [["Mercenary", "S", "A", "A", "Presion frontal permisiva y recuperacion sencilla."], ["Withered Knight", "A", "S", "S", "Resistencia, control de espacio y ancla fiable."], ["Seer", "B", "A", "S", "Informacion y utilidad crecen con la coordinacion."], ["Blackarrow", "A", "A", "A", "Alcance y exploracion para quien lee bien los combates."], ["Shadowstrix", "A", "S", "B", "Burst y movilidad con mas exigencia de ejecucion."], ["Sorcerer", "B", "S", "S", "Presion de zona fuerte, pero menos tolerante en solitario."]]},
            {"type": "rich", "title": "Como se construye esta tier list", "paragraphs": [
                "Primero medimos cuanto perdona una clase un error. Una opcion que conserva salidas despues de fallar es mas facil de recomendar que otra que necesita una apertura perfecta. Por eso Mercenary puede superar a una clase mas llamativa en solo.",
                "Tambien cuenta el valor de las decisiones. Rastreo, control, alcance y retirada fiable pueden ganar una extraccion sin aparecer en una captura de dano. Seer y Withered Knight pesan mas en duo y escuadron porque un aliado puede aprovechar el espacio o la informacion.",
                "Por ultimo observamos la exigencia mecanica. El burst solo vale si puedes iniciar y terminar el intercambio con intencion. Shadowstrix y Sorcerer suben para grupos experimentados y bajan como primera eleccion. La letra describe un uso, no una medicion universal de poder.",
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-modes.webp", "alt": "Ilustracion editorial de cazadores de Mistfall Hunter eligiendo tres rutas nevadas de extraccion", "width": 1024, "height": 1024, "caption": "Ilustracion editorial para comparar modos. Es una imagen conceptual, no un mapa oficial ni una captura de gameplay."},
            {"type": "rich", "title": "Guia rapida para elegir cada clase", "paragraphs": [
                "Elige Mercenary si quieres aprender el bucle de extraccion sin convertir cada error en una perdida. Su trabajo es claro: acercarse, presionar y salir antes de que el combate sea caro. Es una buena base para saber si el problema esta en la clase o en la ruta.",
                "Elige Withered Knight cuando tu grupo necesita un ancla. Aguantar una puerta, comprar tiempo para retirarse o proteger a un aliado fragil vale mas que perseguir dano. En duo, esa consistencia deja una ventana mas clara para explorar o rematar.",
                "Elige Seer o Blackarrow cuando falta informacion. Seer encaja mejor en escuadrones coordinados; Blackarrow recompensa el alcance y un ritmo paciente. Ninguna clase elimina la necesidad de leer el mapa y evitar peleas de poco valor.",
                "Elige Shadowstrix o Sorcerer cuando el grupo ya tiene un plan claro. Shadowstrix favorece flancos y retirada rapida; Sorcerer favorece control de zona y objetivos agrupados. Si no sabes quien inicia y quien sale, una clase mas segura suele rendir mejor.",
            ]},
            {"type": "table", "title": "Elecciones para situaciones comunes", "headers": ["Situacion", "Empieza con", "Motivo"], "rows": [["Primera extraccion solo", "Mercenary", "Rol claro y errores mas recuperables."], ["Ancla segura en duo", "Withered Knight", "Crea tiempo y espacio para el segundo jugador."], ["Utilidad de escuadron", "Seer", "Convierte informacion en decisiones mas seguras."], ["Exploracion a distancia", "Blackarrow", "Permite elegir cuando comprometerse."], ["Burst agresivo en duo", "Shadowstrix o Sorcerer", "Premia una apertura coordinada, pero exige mas."]]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-roles.webp", "alt": "Ilustracion editorial de un cazador frontal, un explorador a distancia y un lanzador de sombras", "width": 1024, "height": 1024, "caption": "Ilustracion conceptual de supervivencia, informacion y burst; no es una revelacion oficial de personajes."},
            {"type": "rich", "title": "Como usar la lista despues de un parche", "paragraphs": [
                "No cambies una clase de tier por un solo clip. Comprueba si el cambio afecta dano, supervivencia, alcance, enfriamientos o la entrada y salida del combate. Una cifra pequena puede importar menos que una interaccion nueva.",
                "Prueba la clase en el modo donde quieres jugar. Un aumento de limpieza en solo no siempre aumenta el valor en escuadron, y un cambio de control puede ser mucho mejor con companeros coordinados. Por eso hay una tabla separada por modo.",
                "Si dos opciones estan cerca, elige el rol que falta y anota el resultado. Esa experiencia contextual vale mas que perseguir un ranking sin explicacion. Actualizaremos la pagina cuando haya notas verificadas o evidencia repetida y clara.",
            ]},
            {"type": "faq", "title": "Preguntas frecuentes sobre la tier list", "items": [["Cual es la mejor clase de Mistfall Hunter?", "Mercenary es el inicio mas seguro para solo; Withered Knight y Seer suben cuando el escuadron necesita ancla o informacion. La mejor clase depende del modo y del rol que falta."], ["Cual es la mejor clase para solo?", "Empieza con Mercenary si buscas una ruta permisiva. Blackarrow o Shadowstrix pueden ser mejores cuando ya controlas distancia, exploracion y retirada."], ["Es oficial esta tier list?", "No. Es una comparacion independiente basada en claridad de rol, tolerancia al error, utilidad de equipo y exigencia de ejecucion. Revisa siempre la version actual."], ["Deben los principiantes elegir solo la categoria S?", "No. Una clase A que puedes explicar y con la que extraes es mejor que una S cuyo timing no entiendes. La tabla sirve para elegir una prueba."], ["Donde comparo todas las clases?", "Consulta la guia de clases para perfiles y el planner para recomendaciones de solo, duo y escuadron. La guia de gameplay explica el bucle de extraccion."]]},
            {"type": "links", "title": "Referencia oficial", "items": [["Mistfall Hunter en Steam", "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", "Referencia oficial de plataforma e identidad del producto.", "noopener"]]},
            {"type": "related", "title": "Guias relacionadas de Mistfall Hunter", "items": [["Guia de clases de Mistfall Hunter", "/es/classes/", "Compara roles, riesgo y opciones para principiantes."], ["Planificador de builds", "/es/build-planner/", "Relaciona la clase con solo, duo o escuadron."], ["Guia de gameplay", "/es/gameplay/", "Entiende el bucle de extraccion."], ["Review de Mistfall Hunter", "/es/review/", "Lee los pros y limites del juego."]]},
        ],
    },
    "ja": {
        "page": {"title": "Mistfall Hunter ティアリスト: モード別おすすめクラス", "description": "ソロ、デュオ、分隊で見るMistfall Hunterのクラスティアリスト。初心者向けの選び方と非公式の評価基準をまとめます。", "h1": "Mistfall Hunter ティアリスト: ソロ・デュオ・分隊のおすすめクラス", "kicker": "Mistfall Hunter クラス比較 | 2026年8月更新"},
        "sections": [
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": "雪の戦場で戦うハンターを描いたMistfall Hunterの公式Steamアート", "caption": "ゲームを確認するための公式Steamアートです。クラス性能や実際のプレイ画面を示すものではありません。"},
            {"type": "rich", "title": "先に結論: 最強クラスはプレイモードで変わる", "paragraphs": [
                "迷ったままソロを始めるなら、Mercenaryが最も扱いやすい出発点です。このファンメイドのMistfall Hunterティアリストでは、前線での役割が分かりやすく、ミスをした後も立て直しやすい点を評価しています。分隊の盾役ならWithered Knight、情報と安全な判断ならSeerが候補になります。",
                "ShadowstrixとSorcererはバースト重視の構成で上位に入りますが、誰にでも最適という意味ではありません。仕掛けるタイミング、位置取り、離脱の判断が必要で、失敗時の代償も大きくなります。Blackarrowは距離と索敵を活かす中間的な選択です。",
                "ここで示すのは公式ランキングではなく、状況別の判断材料です。パッチ、プレイヤーの習熟度、チームの不足役割によって結論は変わります。表を入口にして、クラスガイドとビルドプランナーで実際のランに合わせてください。",
            ]},
            {"type": "table", "title": "モード別Mistfall Hunterティアリスト", "headers": ["クラス", "ソロ", "デュオ", "分隊", "評価理由"], "rows": [["Mercenary", "S", "A", "A", "役割が明確で前線のミスを立て直しやすい。"], ["Withered Knight", "A", "S", "S", "耐久力と空間制御で味方の時間を作る。"], ["Seer", "B", "A", "S", "連携が増えるほど情報と支援の価値が上がる。"], ["Blackarrow", "A", "A", "A", "距離と索敵で戦うタイミングを選べる。"], ["Shadowstrix", "A", "S", "B", "機動力と瞬間火力は高いが離脱の判断が必要。"], ["Sorcerer", "B", "S", "S", "範囲圧力は強いがソロではミスに厳しい。"]]},
            {"type": "rich", "title": "このクラスティアリストの基準", "paragraphs": [
                "最初に見るのは失敗への許容度です。攻撃を外しても次の選択肢が残るクラスは、完璧な初動を要求するクラスより初心者に向きます。そのためソロでは、派手な火力よりMercenaryの安定性を上位に置きます。",
                "次に見るのは判断への貢献です。追跡、空間制御、射程、離脱の安定性は、ダメージ表示に出なくても脱出を助けます。SeerとWithered Knightは、味方が情報や作った空間を利用できるデュオ・分隊で評価が上がります。",
                "最後は操作と実行の難しさです。バーストは、開始と終了を自分で決められるときに価値を持ちます。ShadowstrixとSorcererは経験者の構成で上がり、初回の選択では下がります。これは万能な強さではなく、用途の評価です。",
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-modes.webp", "alt": "雪の中で三つの脱出ルートを選ぶMistfall Hunterのハンターたち", "width": 1024, "height": 1024, "caption": "モード比較を説明するためのコンセプトイラストです。公式マップやゲーム画面ではありません。"},
            {"type": "rich", "title": "クラス別の選び方", "paragraphs": [
                "脱出ループを学びたいソロプレイヤーにはMercenaryが向きます。接近して圧力をかけ、戦闘が高くつく前に離れるという役割が読みやすく、ルート選択の問題とクラス選択の問題を切り分けやすいからです。",
                "味方を守る軸が必要ならWithered Knightを選びます。入口を押さえ、撤退の時間を作り、耐久力の低い味方を守る仕事は、単純なダメージ量とは別の価値があります。デュオでは相方の索敵や追撃の窓も作れます。",
                "情報が不足しているならSeerかBlackarrowです。連携した分隊ならSeer、距離と慎重なペースを好むならBlackarrowが分かりやすい候補です。どちらもマップを読むことや無駄な戦闘を避けることを代替しません。",
                "すでに開始役と撤退役が決まっているチームならShadowstrixかSorcererを試せます。前者は側面攻撃と離脱、後者は範囲制御が得意です。役割を説明できない段階では、理論上のSより安全な選択の方が結果につながります。",
            ]},
            {"type": "table", "title": "状況別の最初の候補", "headers": ["状況", "候補", "理由"], "rows": [["初めてのソロ脱出", "Mercenary", "役割が読みやすく、失敗から戻りやすい。"], ["デュオの前衛", "Withered Knight", "相方のために時間と空間を作る。"], ["連携分隊の支援", "Seer", "情報を移動とターゲット判断につなげる。"], ["遠距離の索敵", "Blackarrow", "戦闘に入るタイミングを選びやすい。"], ["攻撃的なデュオ", "ShadowstrixまたはSorcerer", "計画した初動を高い火力に変えられる。"]]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-roles.webp", "alt": "盾役、遠距離の索敵役、影の魔法役を比較するコンセプトイラスト", "width": 1024, "height": 1024, "caption": "耐久、情報、バーストというトレードオフを示す編集部作成の図です。公式キャラクター紹介ではありません。"},
            {"type": "rich", "title": "パッチ後にティアを読み直す方法", "paragraphs": [
                "一つの動画や一試合だけでクラスを移動させないでください。ダメージ、耐久、射程、クールダウン、戦闘への入り方と出方のどれが変わったのかを確認します。小さな数値変更より、新しい相互作用の方が重要な場合もあります。",
                "使いたいモードで再テストすることも大切です。ソロの処理速度を上げる変更が分隊の価値を上げるとは限らず、制御や情報の変更は連携時に初めて強くなることがあります。このため一つの万能Sではなく、モード別に表を分けています。",
                "二つの候補が近いなら、チームに足りない役割を選び、何が起きたかを記録してください。ランキングを追うより、説明できる経験の方が次のランに役立ちます。公式パッチノートや繰り返し確認できる根拠で境界が変わったときに更新します。",
            ]},
            {"type": "faq", "title": "Mistfall Hunterティアリスト FAQ", "items": [["Mistfall Hunterで最強のクラスはどれですか？", "安全なソロの出発点はMercenaryです。分隊の前衛ならWithered Knight、情報が必要ならSeerが有力ですが、モードと不足している役割によって変わります。"], ["ソロでおすすめのクラスは？", "最も立て直しやすい選択ならMercenaryです。距離管理と索敵に慣れているならBlackarrow、奇襲と離脱に自信があるならShadowstrixも候補になります。"], ["このティアリストは公式ですか？", "いいえ。役割の分かりやすさ、失敗への許容度、チームへの貢献、実行難度を使った独立したファン向け比較です。現在のバージョンも確認してください。"], ["初心者はSだけを選ぶべきですか？", "いいえ。理解して脱出できるAのクラスは、タイミングを理解していないSより役立ちます。表は試す候補を絞るために使ってください。"], ["詳しいクラス比較はどこで読めますか？", "クラスガイドでは役割とリスクを、ビルドプランナーではソロ・デュオ・分隊の方向を比較できます。ゲームプレイガイドでは脱出ループも説明しています。"]]},
            {"type": "links", "title": "公式参照", "items": [["Mistfall Hunter Steam公式ページ", "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", "プラットフォームと製品情報の公式参照先です。", "noopener"]]},
            {"type": "related", "title": "関連するMistfall Hunterガイド", "items": [["Mistfall Hunterクラスガイド", "/ja/classes/", "役割、リスク、初心者向けの方向を比較します。"], ["Mistfall Hunterビルドプランナー", "/ja/build-planner/", "クラスをソロ、デュオ、分隊に合わせます。"], ["Mistfall Hunterゲームプレイガイド", "/ja/gameplay/", "判断の前提になる脱出ループを確認します。"], ["Mistfall Hunterレビュー", "/ja/review/", "ゲームループと購入前の注意点を読みます。"]]},
        ],
    },
    "fr": {
        "page": {"title": "Tier list Mistfall Hunter : meilleures classes", "description": "Une tier list pratique de Mistfall Hunter pour le solo, le duo et l escouade, avec les compromis de role et les choix pour debuter.", "h1": "Tier list Mistfall Hunter : meilleures classes en solo, duo et escouade", "kicker": "Tier list des classes | Mise a jour aout 2026"},
        "sections": [
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": "Illustration Steam officielle de Mistfall Hunter dans un champ enneige", "caption": "Illustration Steam officielle pour identifier le jeu. Elle ne prouve ni l equilibre des classes ni le gameplay."},
            {"type": "rich", "title": "Verdict rapide : la meilleure classe depend du mode", "paragraphs": [
                "Pour commencer en solo avec une marge d erreur raisonnable, Mercenary est le choix le plus simple de cette tier list fan-made. Son role de front est lisible et permet de recuperer apres un mauvais echange. Withered Knight devient le meilleur ancrage pour une equipe, tandis que Seer prend de la valeur quand l information et les appels surs comptent plus que les degats.",
                "Shadowstrix et Sorcerer montent dans une composition orientee burst, mais ils ne gagnent pas automatiquement chaque partie. Ils demandent un bon timing, une position propre et une vraie sortie de combat. Blackarrow offre un compromis utile entre distance, reconnaissance et pression mesuree.",
                "Cette page est une comparaison par situation, pas un classement officiel ni une promesse de meta permanente. Les patchs, le niveau du joueur et le manque de role dans l equipe changent la reponse. Utilisez le tableau comme point de depart, puis verifiez le guide des classes et le planificateur de builds.",
            ]},
            {"type": "table", "title": "Tier list par mode", "headers": ["Classe", "Solo", "Duo", "Escouade", "Pourquoi"], "rows": [["Mercenary", "S", "A", "A", "Pression de front lisible et erreurs plus recuperables."], ["Withered Knight", "A", "S", "S", "Duree, controle de l espace et ancrage fiable."], ["Seer", "B", "A", "S", "Information et utilite progressent avec la coordination."], ["Blackarrow", "A", "A", "A", "Portee et reconnaissance pour choisir son engagement."], ["Shadowstrix", "A", "S", "B", "Burst et mobilite, avec une execution plus exigeante."], ["Sorcerer", "B", "S", "S", "Pression de zone forte, mais moins permissive en solo."]] },
            {"type": "rich", "title": "Notre methode de comparaison", "paragraphs": [
                "Nous regardons d abord la tolerance a l erreur. Une classe qui garde des options apres une attaque ratee est plus facile a recommander a un debutant qu une classe qui exige une ouverture parfaite. C est ce qui place Mercenary devant des options plus spectaculaires en solo.",
                "Nous regardons ensuite la valeur des decisions. Le suivi, le controle d espace, la portee et la sortie fiable peuvent gagner une extraction sans apparaitre dans une capture de degats. Seer et Withered Knight montent quand un allie peut utiliser l information ou l espace cree.",
                "Enfin, l exigence d execution compte. Le burst n est utile que si le joueur sait quand entrer et quand sortir. Shadowstrix et Sorcerer montent chez les groupes experimentes, mais sont moins evidents pour une premiere partie. La lettre de tier decrit un usage, pas une puissance universelle.",
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-modes.webp", "alt": "Illustration editoriale de chasseurs choisissant trois chemins d extraction dans une foret enneigee", "width": 1024, "height": 1024, "caption": "Illustration conceptuelle pour expliquer les modes. Ce n est ni une carte officielle ni une capture de jeu."},
            {"type": "rich", "title": "Choisir une classe selon son besoin", "paragraphs": [
                "Prenez Mercenary pour apprendre la boucle d extraction sans transformer chaque erreur en perte. Son plan est clair : approcher, mettre la pression, puis partir avant que le combat ne devienne trop cher. Il aide aussi a distinguer un probleme de route d un probleme de classe.",
                "Prenez Withered Knight si votre groupe a besoin d une ancre. Tenir une entree, acheter du temps pour le repli ou proteger un allie fragile peut compter davantage qu un total de degats. En duo, cette constance ouvre une fenetre pour la reconnaissance ou la finition.",
                "Prenez Seer ou Blackarrow si l information manque. Seer convient mieux a une escouade coordonnee; Blackarrow convient a un joueur patient qui prefere la distance. Aucun des deux ne remplace la lecture de la carte et l abandon des combats peu rentables.",
                "Prenez Shadowstrix ou Sorcerer lorsque le groupe sait deja qui commence et qui sort. Shadowstrix favorise les flancs et le desengagement; Sorcerer prefere la pression de zone. Sans plan partage, une classe plus sure vaut souvent mieux qu une note theorique S.",
            ]},
            {"type": "table", "title": "Choix rapides", "headers": ["Situation", "Commencer par", "Raison"], "rows": [["Premiere extraction solo", "Mercenary", "Role lisible et erreurs plus faciles a recuperer."], ["Ancre en duo", "Withered Knight", "Cree du temps et de l espace pour le partenaire."], ["Utilite d escouade", "Seer", "Transforme l information en deplacements plus surs."], ["Reconnaissance a distance", "Blackarrow", "Permet de choisir le moment de s engager."], ["Burst agressif en duo", "Shadowstrix ou Sorcerer", "Convertit une ouverture preparee avec plus d exigence."]] },
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-roles.webp", "alt": "Illustration editoriale comparant un chasseur defensif, un eclaireur a distance et un lanceur d ombre", "width": 1024, "height": 1024, "caption": "Illustration conceptuelle des compromis entre survie, information et burst; ce n est pas une revelation officielle."},
            {"type": "rich", "title": "Relire la tier list apres un patch", "paragraphs": [
                "Ne changez pas une classe de tier apres un seul clip. Verifiez si le changement touche les degats, la survie, la portee, les temps de recharge ou la facon d entrer et de sortir d un combat. Une petite valeur peut etre moins importante qu une nouvelle interaction.",
                "Retestez la classe dans le mode vise. Une amelioration de nettoyage en solo ne renforce pas forcement une equipe, tandis qu un changement de controle peut devenir decisif avec des coequipiers coordonnes. C est pourquoi la page separe solo, duo et escouade.",
                "Quand deux choix sont proches, prenez le role qui manque et notez le resultat. Cette experience expliquee vaut mieux qu un classement sans contexte. La page sera mise a jour avec des notes officielles ou des preuves de gameplay repetees et comprehensibles.",
            ]},
            {"type": "faq", "title": "FAQ de la tier list Mistfall Hunter", "items": [["Quelle est la meilleure classe de Mistfall Hunter ?", "Mercenary est le depart le plus sur en solo; Withered Knight et Seer montent quand une escouade a besoin d une ancre ou d information. Le meilleur choix depend du mode et du role absent."], ["Quelle est la meilleure classe en solo ?", "Commencez par Mercenary pour une route permissive. Blackarrow ou Shadowstrix peuvent etre meilleurs si vous maitrisez deja la distance, la reconnaissance et le repli."], ["Cette tier list est-elle officielle ?", "Non. C est une comparaison independante basee sur la clarte du role, la tolerance a l erreur, l utilite d equipe et l exigence d execution. Verifiez toujours la version actuelle."], ["Les debutants doivent-ils choisir uniquement le tier S ?", "Non. Une classe A que vous comprenez et avec laquelle vous extrayez vaut mieux qu une classe S dont le timing reste flou. Utilisez la liste pour choisir quoi tester."], ["Ou comparer les classes en detail ?", "Le guide des classes decrit les roles et les risques, le planificateur propose des directions solo, duo et escouade, et le guide gameplay explique la boucle d extraction."]]},
            {"type": "links", "title": "Reference officielle", "items": [["Mistfall Hunter sur Steam", "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", "Reference officielle pour la plateforme et l identite du produit.", "noopener"]]},
            {"type": "related", "title": "Guides Mistfall Hunter associes", "items": [["Guide des classes Mistfall Hunter", "/fr/classes/", "Comparer roles, risques et choix debutants."], ["Planificateur de builds Mistfall Hunter", "/fr/build-planner/", "Associer une classe au solo, duo ou escouade."], ["Guide gameplay Mistfall Hunter", "/fr/gameplay/", "Comprendre la boucle d extraction."], ["Review Mistfall Hunter", "/fr/review/", "Voir les compromis du jeu et de l achat."]]},
        ],
    },
    "de": {
        "page": {"title": "Mistfall Hunter Tier List: Beste Klassen nach Modus", "description": "Eine praktische Mistfall Hunter Tier List fur Solo, Duo und Gruppe mit Rollen, Risiken, Einsteigerwahl und einer nicht offiziellen Bewertungsmethode.", "h1": "Mistfall Hunter Tier List: Beste Klassen fur Solo, Duo und Gruppe", "kicker": "Mistfall Hunter Klassenvergleich | Aktualisiert August 2026"},
        "sections": [
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": "Offizielle Steam-Grafik von Mistfall Hunter mit Jägern in einer verschneiten Landschaft", "caption": "Offizielle Steam-Grafik zur Identifikation des Spiels. Sie ist kein Beleg fur Balance und kein Gameplay-Screenshot."},
            {"type": "rich", "title": "Schnelles Urteil: Die beste Klasse hangt vom Run ab", "paragraphs": [
                "Wenn du solo einen verzeihenden Start suchst, ist Mercenary die sicherste Empfehlung dieser fan-made Mistfall Hunter Tier List. Der Frontrollen-Plan ist leicht zu lesen und erlaubt mehr Erholung nach einem schlechten Trade. Withered Knight wird zum Anker fur Gruppen, wahrend Seer gewinnt, wenn Information und sichere Calls wichtiger sind als roher Schaden.",
                "Shadowstrix und Sorcerer steigen in einer Burst-Liste, sind aber keine automatischen Gewinner. Beide verlangen Timing, Positionierung und einen klaren Ausstieg. Blackarrow liegt dazwischen: Reichweite und Aufklarung sind stark, aber nur wenn der Spieler den richtigen Kampf auswahlt.",
                "Diese Seite ist keine offizielle Tier List und kein dauerhaftes Meta-Versprechen. Patches, Erfahrung und die Lucke in der Gruppenrolle verandern das Ergebnis. Nutze die Tabelle als Startpunkt und kombiniere sie mit Klassen-Guide und Build-Planer.",
            ]},
            {"type": "table", "title": "Tier List nach Spielmodus", "headers": ["Klasse", "Solo", "Duo", "Gruppe", "Warum"], "rows": [["Mercenary", "S", "A", "A", "Verzeihender Frontdruck und einfache Erholung."], ["Withered Knight", "A", "S", "S", "Halt Raum, uberlebt Trades und schutzt Verbundete."], ["Seer", "B", "A", "S", "Information und Nutzen wachsen mit der Koordination."], ["Blackarrow", "A", "A", "A", "Reichweite und Scouting erlauben bewusste Kampfe."], ["Shadowstrix", "A", "S", "B", "Burst und Mobilitat mit hoherem Timing-Risiko."], ["Sorcerer", "B", "S", "S", "Zonendruck ist stark, allein aber weniger verzeihend."]] },
            {"type": "rich", "title": "So entsteht der Klassenvergleich", "paragraphs": [
                "Zuerst bewerten wir Fehlertoleranz. Eine Klasse mit Auswegen nach einem verfehlten Angriff ist fur Einsteiger leichter als eine Klasse mit perfektem Startfenster. Deshalb kann Mercenary solo vor einer auffalligeren Schadensklasse landen.",
                "Dann zahlt der Wert von Entscheidungen. Tracking, Raumkontrolle, Reichweite und ein sicherer Ruckzug konnen eine Extraktion gewinnen, ohne im Schadensbild aufzutauchen. Seer und Withered Knight steigen, wenn Verbundete ihre Information oder den geschaffenen Raum nutzen.",
                "Drittens zahlt die Ausfuhrung. Burst ist nur dann stark, wenn man bewusst ein- und aussteigen kann. Shadowstrix und Sorcerer steigen bei erfahrenen Gruppen, sind aber keine sichere erste Wahl. Das Tier beschreibt einen Einsatz, keine universelle Macht.",
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-modes.webp", "alt": "Editoriale Illustration von Mistfall Hunter Jägern an drei verschneiten Extraktionswegen", "width": 1024, "height": 1024, "caption": "Konzeptbild fur den Modusvergleich. Keine offizielle Karte und kein echter Gameplay-Screenshot."},
            {"type": "rich", "title": "Welche Klasse passt zu welchem Bedarf?", "paragraphs": [
                "Mercenary passt, wenn du den Extraktionsloop lernen willst, ohne jeden Fehler teuer zu bezahlen. Die Rolle ist klar: nah heran, Druck ausuben und gehen, bevor der Kampf ungunstig wird. So lasst sich Klassenwahl von Routenfehlern trennen.",
                "Withered Knight passt, wenn die Gruppe einen Anker braucht. Einen Eingang halten, Zeit fur den Ruckzug kaufen oder einen fragilen Verbundeten schutzen kann wichtiger sein als die hochste Schadenszahl. Im Duo entsteht so ein Fenster fur Scout oder Finisher.",
                "Seer oder Blackarrow passen, wenn Information fehlt. Seer ist fur koordinierte Gruppen stark; Blackarrow belohnt Distanz und Geduld. Beide ersetzen nicht das Lesen der Karte und das Vermeiden schlechter Kampfe.",
                "Shadowstrix oder Sorcerer passen, wenn das Team bereits einen Plan fur Start und Ausstieg hat. Shadowstrix spielt Flanken und schnelle Ruckzuge, Sorcerer Zonen. Ohne gemeinsame Rollenbeschreibung ist eine sichere Klasse oft besser als ein theoretisches S.",
            ]},
            {"type": "table", "title": "Schnelle Wahl fur typische Situationen", "headers": ["Situation", "Starte mit", "Grund"], "rows": [["Erste Solo-Extraktion", "Mercenary", "Klare Aufgabe und gut verzeihende Fehlerkurve."], ["Duo-Anker", "Withered Knight", "Schafft Zeit und Raum fur den Partner."], ["Nutzen in der Gruppe", "Seer", "Macht Information fur Bewegung und Calls nutzbar."], ["Fernkampf-Scouting", "Blackarrow", "Der Spieler entscheidet bewusster uber den Einstieg."], ["Aggressives Duo", "Shadowstrix oder Sorcerer", "Verwandelt eine geplante Offnung in Burst mit mehr Risiko."]] },
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-roles.webp", "alt": "Editoriale Illustration mit Frontkampfer, Fernkampfer und Schattenzauberer in einer verschneiten Mistfall-Welt", "width": 1024, "height": 1024, "caption": "Konzeptbild fur die Abwagung von Uberleben, Information und Burst; keine offizielle Charaktervorstellung."},
            {"type": "rich", "title": "Tier nach einem Patch neu lesen", "paragraphs": [
                "Verschiebe eine Klasse nicht wegen eines einzelnen Clips. Prufe Schaden, Haltbarkeit, Reichweite, Cooldowns und die Art, wie die Klasse einen Kampf beginnt und beendet. Eine kleine Zahl kann weniger wichtig sein als eine neue Interaktion.",
                "Teste im geplanten Modus. Schnelleres Solo-Clearing verbessert nicht automatisch den Gruppenwert, und eine Kontrollanderung kann erst mit koordinierten Partnern stark werden. Darum trennt diese Seite Solo, Duo und Gruppe.",
                "Wenn zwei Optionen nah beieinander liegen, nimm die fehlende Rolle und notiere das Ergebnis. Erklarbare Erfahrung ist hilfreicher als ein Ranking ohne Kontext. Aktualisiert wird bei verifizierten Patchnotizen oder wiederholbaren Gameplay-Belegen.",
            ]},
            {"type": "faq", "title": "Mistfall Hunter Tier List FAQ", "items": [["Welche Klasse ist die beste in Mistfall Hunter?", "Mercenary ist der sicherste Solo-Start. Withered Knight und Seer steigen, wenn eine Gruppe einen Anker oder Information braucht. Die beste Klasse hangt von Modus, Erfahrung und Teamlucke ab."], ["Welche Klasse ist am besten fur Solo?", "Starte mit Mercenary, wenn du eine verzeihende Frontrolle willst. Blackarrow oder Shadowstrix passen besser, wenn Abstand, Scouting und Ruckzug schon sitzen."], ["Ist diese Tier List offiziell?", "Nein. Sie ist ein unabhangiger Vergleich nach Rollen-Klarheit, Fehlertoleranz, Teamnutzen und Ausfuhrungsbedarf. Prufe die aktuelle Version vor einer festen Entscheidung."], ["Sollten Anfanger nur S-Tier spielen?", "Nein. Eine verstandene A-Tier-Klasse, mit der du extrahierst, ist besser als ein S-Tier-Pick ohne Timing-Verstandnis. Nutze die Liste zum Auswahlen eines Tests."], ["Wo kann ich die Klassen genauer vergleichen?", "Der Klassen-Guide beschreibt Rollen und Risiko, der Build-Planer ordnet Solo, Duo und Gruppe zu, und der Gameplay-Guide erklart den Extraktionsloop."]]},
            {"type": "links", "title": "Offizielle Referenz", "items": [["Mistfall Hunter auf Steam", "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", "Offizielle Quelle fur Plattform und Produktidentitat.", "noopener"]]},
            {"type": "related", "title": "Verwandte Mistfall Hunter Guides", "items": [["Mistfall Hunter Klassen-Guide", "/de/classes/", "Rollen, Risiko und Einsteigerwahl vergleichen."], ["Mistfall Hunter Build-Planer", "/de/build-planner/", "Klasse auf Solo, Duo oder Gruppe abstimmen."], ["Mistfall Hunter Gameplay-Guide", "/de/gameplay/", "Den Extraktionsloop hinter den Entscheidungen verstehen."], ["Mistfall Hunter Review", "/de/review/", "Spielschleife und Kaufabwägung lesen."]]},
        ],
    },
    "pt": {
        "page": {"title": "Tier list Mistfall Hunter: melhores classes", "description": "Tier list pratica de Mistfall Hunter para solo, dupla e esquadrao, com riscos, escolhas para iniciantes e metodo nao oficial.", "h1": "Tier list Mistfall Hunter: melhores classes para solo, dupla e esquadrao", "kicker": "Tier list de classes | Atualizada em agosto de 2026"},
        "sections": [
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": "Arte oficial da Steam de Mistfall Hunter em um campo nevado", "caption": "Arte oficial da Steam usada para identificar o jogo. Ela nao prova balanceamento nem e uma captura de gameplay."},
            {"type": "rich", "title": "Veredito rapido: a melhor classe depende da run", "paragraphs": [
                "Para comecar no solo com mais margem para errar, Mercenary e a escolha mais permissiva desta tier list fan-made de Mistfall Hunter. A funcao de frente e facil de entender e ajuda a recuperar uma troca ruim. Withered Knight e melhor como ancora do grupo, enquanto Seer cresce quando informacao e chamadas seguras importam mais que dano bruto.",
                "Shadowstrix e Sorcerer sobem em uma lista focada em burst, mas nao vencem automaticamente. Eles exigem timing, posicionamento e uma saida clara. Blackarrow fica no meio: alcance e reconhecimento sao uteis, mas dependem de escolher a luta certa.",
                "Esta e uma comparacao por situacao, nao uma tier list oficial nem uma promessa de meta permanente. Patches, habilidade e a funcao que falta no grupo mudam a resposta. Use a tabela como ponto de partida e depois combine o guia de classes com o planejador de builds.",
            ]},
            {"type": "table", "title": "Tier list por modo", "headers": ["Classe", "Solo", "Dupla", "Esquadrao", "Por que"], "rows": [["Mercenary", "S", "A", "A", "Pressao frontal clara e erro mais recuperavel."], ["Withered Knight", "A", "S", "S", "Resistencia, controle de espaco e ancora confiavel."], ["Seer", "B", "A", "S", "Informacao e utilidade aumentam com coordenacao."], ["Blackarrow", "A", "A", "A", "Alcance e reconhecimento para escolher o combate."], ["Shadowstrix", "A", "S", "B", "Burst e mobilidade com maior exigencia de execucao."], ["Sorcerer", "B", "S", "S", "Pressao de area forte, mas menos perdoavel sozinho."]] },
            {"type": "rich", "title": "Como esta tier list e montada", "paragraphs": [
                "Primeiro avaliamos a tolerancia ao erro. Uma classe que conserva saidas depois de errar um ataque e mais simples para iniciantes do que uma que precisa de uma abertura perfeita. Por isso Mercenary pode ficar acima de uma opcao mais chamativa no solo.",
                "Depois avaliamos o valor das decisoes. Rastreamento, controle de espaco, alcance e retirada segura podem ganhar uma extracao sem aparecer no dano. Seer e Withered Knight ganham peso quando aliados usam a informacao ou o espaco criado.",
                "Por fim, observamos a exigencia de execucao. Burst vale quando voce consegue entrar e sair de proposito. Shadowstrix e Sorcerer sobem com grupos experientes, mas nao sao a primeira escolha mais segura. A letra descreve uso, nao poder universal.",
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-modes.webp", "alt": "Ilustracao editorial de cacadores escolhendo tres rotas nevadas de extracao", "width": 1024, "height": 1024, "caption": "Ilustracao conceitual para explicar os modos. Nao e mapa oficial nem captura de jogo."},
            {"type": "rich", "title": "Escolha por necessidade", "paragraphs": [
                "Use Mercenary para aprender o ciclo de extracao sem transformar cada erro em perda. A funcao e clara: aproximar, pressionar e sair antes de o combate ficar caro. Ele tambem ajuda a separar problema de rota de problema de classe.",
                "Use Withered Knight quando o grupo precisa de uma ancora. Segurar uma entrada, comprar tempo para recuar ou proteger um aliado fragil pode valer mais que liderar o dano. Em dupla, isso abre espaco para o parceiro explorar ou finalizar.",
                "Use Seer ou Blackarrow quando falta informacao. Seer combina com esquadroes coordenados; Blackarrow recompensa distancia e paciencia. Nenhum dos dois substitui a leitura do mapa ou a escolha de evitar lutas ruins.",
                "Use Shadowstrix ou Sorcerer quando o grupo ja sabe quem inicia e quem sai. Shadowstrix favorece flancos e recuo; Sorcerer favorece controle de area. Sem plano compartilhado, uma classe segura costuma valer mais que um S teorico.",
            ]},
            {"type": "table", "title": "Escolhas rapidas", "headers": ["Situacao", "Comece com", "Motivo"], "rows": [["Primeira extracao solo", "Mercenary", "Funcao clara e erros mais recuperaveis."], ["Ancoragem em dupla", "Withered Knight", "Cria tempo e espaco para o parceiro."], ["Utilidade no esquadrao", "Seer", "Transforma informacao em movimento seguro."], ["Reconhecimento a distancia", "Blackarrow", "Permite decidir quando entrar."], ["Burst agressivo em dupla", "Shadowstrix ou Sorcerer", "Converte uma abertura planejada com mais risco."]] },
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-roles.webp", "alt": "Ilustracao editorial comparando cacador de frente, batedor a distancia e conjurador das sombras", "width": 1024, "height": 1024, "caption": "Ilustracao conceitual dos compromissos entre sobrevivencia, informacao e burst; nao e revelacao oficial."},
            {"type": "rich", "title": "Como reler a lista depois de um patch", "paragraphs": [
                "Nao mova uma classe por causa de um clipe. Confira se a mudanca afeta dano, sobrevivencia, alcance, recarga ou a forma de entrar e sair do combate. Uma pequena alteracao numerica pode importar menos que uma interacao nova.",
                "Teste no modo em que voce pretende jogar. Uma limpeza mais rapida no solo nao melhora automaticamente o esquadrao, enquanto controle pode valer mais com companheiros coordenados. Por isso a pagina separa solo, dupla e esquadrao.",
                "Quando duas opcoes ficam proximas, escolha a funcao que falta e registre o resultado. Experiencia explicada e melhor que perseguir ranking sem contexto. A pagina sera atualizada com notas oficiais ou evidencia repetida e compreensivel.",
            ]},
            {"type": "faq", "title": "Perguntas frequentes sobre a tier list de Mistfall Hunter", "items": [["Qual e a melhor classe de Mistfall Hunter?", "Mercenary e o inicio mais seguro no solo; Withered Knight e Seer sobem quando o grupo precisa de ancora ou informacao. A melhor escolha depende do modo e da funcao ausente."], ["Qual e a melhor classe para solo?", "Comece com Mercenary para uma rota perdoavel. Blackarrow ou Shadowstrix podem ser melhores quando voce ja domina distancia, reconhecimento e retirada."], ["Esta tier list e oficial?", "Nao. E uma comparacao independente baseada em clareza de funcao, tolerancia ao erro, utilidade de equipe e exigencia de execucao. Confira a versao atual antes de decidir."], ["Iniciantes devem escolher apenas o tier S?", "Nao. Uma classe A que voce entende e com a qual consegue extrair e melhor que uma S cujo timing ainda nao conhece. Use a lista para escolher um teste."], ["Onde comparar as classes em detalhes?", "O guia de classes explica papeis e riscos, o planejador combina solo, dupla e esquadrao, e o guia de gameplay explica o ciclo de extracao."]]},
            {"type": "links", "title": "Referencia oficial", "items": [["Mistfall Hunter na Steam", "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", "Fonte oficial para plataforma e identidade do produto.", "noopener"]]},
            {"type": "related", "title": "Guias relacionados de Mistfall Hunter", "items": [["Guia de classes de Mistfall Hunter", "/pt/classes/", "Compare papeis, risco e escolhas para iniciantes."], ["Planejador de builds", "/pt/build-planner/", "Combine a classe com solo, dupla ou esquadrao."], ["Guia de gameplay", "/pt/gameplay/", "Entenda o ciclo de extracao."], ["Review de Mistfall Hunter", "/pt/review/", "Leia os compromissos do jogo e da compra."]]},
        ],
    },
    "ko": {
        "page": {"title": "Mistfall Hunter 티어표: 모드별 추천 직업", "description": "솔로, 듀오, 파티 기준으로 Mistfall Hunter 직업을 비교하는 실전 티어표입니다. 초보자 선택과 비공식 평가 기준을 함께 설명합니다.", "h1": "Mistfall Hunter 티어표: 솔로·듀오·파티 추천 직업", "kicker": "Mistfall Hunter 직업 비교 | 2026년 8월 업데이트"},
        "sections": [
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": "눈 덮인 전장에서 싸우는 Mistfall Hunter 공식 Steam 아트", "caption": "게임을 확인하기 위한 공식 Steam 아트입니다. 직업 밸런스나 실제 플레이 화면의 근거는 아닙니다."},
            {"type": "rich", "title": "먼저 결론: 최고의 직업은 모드에 따라 다릅니다", "paragraphs": [
                "솔로를 처음 시작하며 실수를 조금 더 허용받고 싶다면 Mercenary가 가장 편한 출발점입니다. 이 팬메이드 Mistfall Hunter 티어표에서는 전방 역할이 분명하고 나쁜 교환 뒤에도 회복하기 쉽다는 점을 높게 봅니다. 파티의 버팀목이 필요하면 Withered Knight, 정보와 안전한 판단이 필요하면 Seer가 올라갑니다.",
                "Shadowstrix와 Sorcerer는 폭발적인 피해를 원하는 구성에서 상위권이지만 자동으로 정답은 아닙니다. 진입 타이밍, 위치 선정, 이탈 판단이 필요하고 실패 비용도 큽니다. Blackarrow는 사거리와 정찰을 이용해 싸움을 고르는 중간 선택입니다.",
                "이 표는 공식 랭킹이나 영구적인 메타 선언이 아니라 상황별 판단 자료입니다. 패치, 숙련도, 파티에 부족한 역할에 따라 결과가 바뀝니다. 표를 시험할 후보로 쓰고 직업 가이드와 빌드 플래너로 실제 런에 맞춰 보세요.",
            ]},
            {"type": "table", "title": "모드별 Mistfall Hunter 티어표", "headers": ["직업", "솔로", "듀오", "파티", "이유"], "rows": [["Mercenary", "S", "A", "A", "역할이 쉽고 전방 실수를 회복하기 좋습니다."], ["Withered Knight", "A", "S", "S", "내구도와 공간 제어로 아군의 시간을 만듭니다."], ["Seer", "B", "A", "S", "협력이 많아질수록 정보와 지원 가치가 커집니다."], ["Blackarrow", "A", "A", "A", "사거리와 정찰로 교전 시점을 고릅니다."], ["Shadowstrix", "A", "S", "B", "기동성과 폭딜이 강하지만 실행 난도가 높습니다."], ["Sorcerer", "B", "S", "S", "범위 압박은 강하지만 혼자서는 실수를 덜 용납합니다."]] },
            {"type": "rich", "title": "이 직업 티어표의 기준", "paragraphs": [
                "첫 번째 기준은 실수 허용도입니다. 공격을 빗나가도 다음 선택지가 남는 직업은 완벽한 첫 진입이 필요한 직업보다 초보자에게 쉽습니다. 그래서 솔로에서는 화려한 피해보다 Mercenary의 안정성을 높게 평가합니다.",
                "두 번째는 판단에 주는 가치입니다. 추적, 공간 제어, 사거리, 안정적인 후퇴는 피해량 화면에 보이지 않아도 탈출을 결정합니다. Seer와 Withered Knight는 아군이 정보나 만들어진 공간을 활용할 수 있을 때 듀오와 파티에서 강해집니다.",
                "세 번째는 실행 난도입니다. 폭딜은 언제 들어가고 나올지 스스로 정할 수 있을 때 가치가 있습니다. Shadowstrix와 Sorcerer는 숙련된 파티에서 올라가지만 첫 선택으로는 더 어렵습니다. 티어는 절대적인 힘이 아니라 사용 조건을 나타냅니다.",
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-modes.webp", "alt": "세 갈래의 눈 덮인 탈출 경로를 고르는 Mistfall Hunter 사냥꾼들의 편집 일러스트", "width": 1024, "height": 1024, "caption": "모드별 선택을 설명하는 콘셉트 일러스트입니다. 공식 지도나 실제 플레이 캡처가 아닙니다."},
            {"type": "rich", "title": "상황별 직업 선택", "paragraphs": [
                "추출 루프를 배우면서 실수를 줄이고 싶다면 Mercenary를 고르세요. 접근하고 압박한 뒤 싸움이 비싸지기 전에 빠지는 역할이 분명합니다. 클래스 문제와 루트 문제를 분리해 보기에도 좋은 기준점입니다.",
                "파티에 버팀목이 필요하면 Withered Knight를 고르세요. 입구를 지키고 후퇴 시간을 벌며 취약한 아군을 보호하는 일은 피해량 1위와 다른 가치입니다. 듀오에서는 파트너가 정찰하거나 마무리할 공간을 만듭니다.",
                "정보가 부족하면 Seer 또는 Blackarrow를 고르세요. 협력적인 파티에는 Seer, 거리와 신중한 속도를 좋아하면 Blackarrow가 맞습니다. 어느 쪽도 지도 읽기와 가치 낮은 교전 회피를 대신하지는 않습니다.",
                "팀이 누가 시작하고 누가 빠지는지 이미 정했다면 Shadowstrix 또는 Sorcerer를 시험할 수 있습니다. 전자는 측면 공격과 이탈, 후자는 범위 제어에 강합니다. 공통 계획이 없다면 이론상 S보다 안전한 직업이 더 잘 맞습니다.",
            ]},
            {"type": "table", "title": "상황별 빠른 선택", "headers": ["상황", "먼저 선택", "이유"], "rows": [["첫 솔로 탈출", "Mercenary", "역할이 분명하고 실수 회복이 쉽습니다."], ["듀오 전방", "Withered Knight", "파트너를 위해 시간과 공간을 만듭니다."], ["파티 지원", "Seer", "정보를 이동과 타깃 판단으로 연결합니다."], ["원거리 정찰", "Blackarrow", "교전에 들어갈 시점을 직접 고릅니다."], ["공격적인 듀오", "Shadowstrix 또는 Sorcerer", "계획한 시작을 높은 피해로 바꾸지만 어렵습니다."]] },
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-roles.webp", "alt": "방패 전방 직업, 원거리 정찰 직업, 그림자 마법 직업을 비교하는 편집 일러스트", "width": 1024, "height": 1024, "caption": "생존, 정보, 폭딜의 교환을 보여 주는 콘셉트 이미지이며 공식 캐릭터 공개가 아닙니다."},
            {"type": "rich", "title": "패치 후 티어를 다시 읽는 법", "paragraphs": [
                "한 개의 영상이나 경기만 보고 직업을 옮기지 마세요. 피해, 생존력, 사거리, 재사용 대기시간, 교전 진입과 이탈 방식 중 무엇이 바뀌었는지 먼저 확인합니다. 작은 수치보다 새로운 상호작용이 더 중요할 수도 있습니다.",
                "원하는 모드에서 다시 시험해야 합니다. 솔로 처리 속도가 빨라져도 파티 가치가 자동으로 오르지는 않고, 제어 변화는 협력하는 아군이 있을 때 더 강해질 수 있습니다. 그래서 이 페이지는 하나의 S가 아니라 모드별 표를 사용합니다.",
                "두 선택지가 비슷하면 파티에 부족한 역할을 고르고 결과를 기록하세요. 설명할 수 있는 경험이 맥락 없는 순위를 좇는 것보다 다음 런에 도움이 됩니다. 확인된 패치 노트와 반복 가능한 플레이 근거가 바뀌면 페이지도 갱신합니다.",
            ]},
            {"type": "faq", "title": "Mistfall Hunter 티어표 FAQ", "items": [["Mistfall Hunter에서 최고의 직업은 무엇인가요?", "안전한 솔로 시작은 Mercenary입니다. 파티에 전방이 필요하면 Withered Knight, 정보가 부족하면 Seer가 올라가지만 모드와 부족한 역할에 따라 달라집니다."], ["솔로 추천 직업은 무엇인가요?", "가장 실수 허용도가 높은 시작은 Mercenary입니다. 거리와 정찰에 익숙하다면 Blackarrow, 기습과 이탈 타이밍을 이해한다면 Shadowstrix도 선택할 수 있습니다."], ["이 티어표는 공식인가요?", "아닙니다. 역할 이해도, 실수 허용도, 팀 유틸리티, 실행 난도를 기준으로 한 독립적인 팬 비교입니다. 최종 결정 전 현재 버전의 공지를 확인하세요."], ["초보자는 S 티어만 골라야 하나요?", "아닙니다. 이해하고 탈출할 수 있는 A 티어가 타이밍을 모르는 S 티어보다 좋습니다. 표는 시험할 대상을 좁히는 데 사용하세요."], ["직업을 더 자세히 비교하려면 어디를 보나요?", "직업 가이드는 역할과 위험을, 빌드 플래너는 솔로·듀오·파티 방향을, 게임플레이 가이드는 추출 루프를 설명합니다."]]},
            {"type": "links", "title": "공식 참고", "items": [["Steam 공식 Mistfall Hunter", "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", "플랫폼과 제품 정보를 확인하는 공식 출처입니다.", "noopener"]]},
            {"type": "related", "title": "관련 Mistfall Hunter 가이드", "items": [["Mistfall Hunter 직업 가이드", "/ko/classes/", "역할, 위험도와 초보자 방향을 비교합니다."], ["Mistfall Hunter 빌드 플래너", "/ko/build-planner/", "직업을 솔로, 듀오, 파티에 맞춥니다."], ["Mistfall Hunter 게임플레이 가이드", "/ko/gameplay/", "선택의 배경이 되는 추출 루프를 봅니다."], ["Mistfall Hunter 리뷰", "/ko/review/", "게임 루프와 구매 전 tradeoff를 확인합니다."]]},
        ],
    },
    "it": {
        "page": {"title": "Tier list Mistfall Hunter: migliori classi", "description": "Tier list pratica di Mistfall Hunter per solo, duo e squadra, con rischi, scelte per principianti e metodo di valutazione non ufficiale.", "h1": "Tier list Mistfall Hunter: migliori classi per solo, duo e squadra", "kicker": "Tier list delle classi | Aggiornata agosto 2026"},
        "sections": [
            {"type": "image", "src": "images/mistfall/mistfall-hunter-steam-hero.webp", "alt": "Artwork ufficiale Steam di Mistfall Hunter in un campo innevato", "caption": "Artwork ufficiale Steam usato per identificare il gioco. Non dimostra il bilanciamento e non e una schermata di gameplay."},
            {"type": "rich", "title": "Verdetto rapido: la classe migliore dipende dalla run", "paragraphs": [
                "Se vuoi iniziare in solo con piu margine d errore, Mercenary e la scelta piu semplice di questa tier list fan-made di Mistfall Hunter. Il ruolo frontale e leggibile e aiuta a recuperare dopo uno scambio sbagliato. Withered Knight diventa l ancora migliore per una squadra, mentre Seer cresce quando informazione e chiamate sicure contano piu del danno.",
                "Shadowstrix e Sorcerer salgono in una lista orientata al burst, ma non sono vincitori automatici. Richiedono timing, posizione e una vera via d uscita. Blackarrow offre un compromesso tra distanza, ricognizione e pressione controllata.",
                "Questa pagina e una comparazione per scenari, non una tier list ufficiale e non una promessa di meta permanente. Patch, abilita del giocatore e ruolo mancante nel gruppo cambiano il risultato. Usa la tabella come punto di partenza, poi verifica la guida classi e il build planner.",
            ]},
            {"type": "table", "title": "Tier list per modalita", "headers": ["Classe", "Solo", "Duo", "Squadra", "Perche"], "rows": [["Mercenary", "S", "A", "A", "Pressione frontale chiara e errori piu recuperabili."], ["Withered Knight", "A", "S", "S", "Resistenza, controllo dello spazio e ruolo di ancora."], ["Seer", "B", "A", "S", "Informazione e utilita crescono con il coordinamento."], ["Blackarrow", "A", "A", "A", "Distanza e ricognizione per scegliere lo scontro."], ["Shadowstrix", "A", "S", "B", "Burst e mobilita con maggiore richiesta di esecuzione."], ["Sorcerer", "B", "S", "S", "Pressione ad area forte, ma meno permissiva da solo."]] },
            {"type": "rich", "title": "Come costruiamo questa tier list", "paragraphs": [
                "Prima valutiamo la tolleranza all errore. Una classe che mantiene delle uscite dopo un attacco fallito e piu facile per un principiante di una classe che richiede un apertura perfetta. Per questo Mercenary puo superare un opzione piu spettacolare in solo.",
                "Poi valutiamo il valore delle decisioni. Tracking, controllo dello spazio, portata e ritirata affidabile possono vincere un estrazione senza apparire nei danni. Seer e Withered Knight valgono di piu quando un alleato usa le informazioni o lo spazio creato.",
                "Infine consideriamo la difficolta di esecuzione. Il burst conta quando sai entrare e uscire di proposito. Shadowstrix e Sorcerer salgono con gruppi esperti, ma non sono la scelta piu sicura per la prima partita. Il tier descrive un uso, non una forza universale.",
            ]},
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-modes.webp", "alt": "Illustrazione editoriale di cacciatori che scelgono tre percorsi innevati di estrazione", "width": 1024, "height": 1024, "caption": "Illustrazione concettuale per spiegare le modalita. Non e una mappa ufficiale o una schermata di gioco."},
            {"type": "rich", "title": "Scegliere la classe in base al bisogno", "paragraphs": [
                "Scegli Mercenary se vuoi imparare il ciclo di estrazione senza trasformare ogni errore in una perdita. Il compito e chiaro: avvicinarsi, fare pressione e uscire prima che il combattimento costi troppo. E un buon riferimento per separare un problema di rotta da un problema di classe.",
                "Scegli Withered Knight se alla squadra serve un ancora. Tenere un ingresso, comprare tempo per la ritirata o proteggere un alleato fragile puo valere piu del danno massimo. In duo crea una finestra per la ricognizione o la chiusura dello scontro.",
                "Scegli Seer o Blackarrow se manca informazione. Seer e piu adatto a squadre coordinate; Blackarrow premia distanza e pazienza. Nessuno dei due sostituisce la lettura della mappa o la scelta di evitare scontri poco utili.",
                "Scegli Shadowstrix o Sorcerer quando il gruppo sa gia chi inizia e chi esce. Shadowstrix preferisce fianchi e ritirate rapide; Sorcerer il controllo dell area. Senza un piano comune, una classe sicura vale spesso piu di un S teorico.",
            ]},
            {"type": "table", "title": "Scelte rapide", "headers": ["Situazione", "Inizia con", "Motivo"], "rows": [["Prima estrazione solo", "Mercenary", "Ruolo chiaro e errori piu facili da recuperare."], ["Ancora in duo", "Withered Knight", "Crea tempo e spazio per il compagno."], ["Utilita di squadra", "Seer", "Trasforma l informazione in movimento sicuro."], ["Ricognizione a distanza", "Blackarrow", "Permette di decidere quando entrare."], ["Duo aggressivo", "Shadowstrix o Sorcerer", "Converte un apertura preparata con piu rischio."]] },
            {"type": "image", "src": "images/mistfall/mistfall-hunter-tier-list-roles.webp", "alt": "Illustrazione editoriale di un combattente con scudo, uno scout a distanza e un incantatore d ombra", "width": 1024, "height": 1024, "caption": "Illustrazione concettuale dei compromessi tra sopravvivenza, informazione e burst; non e una rivelazione ufficiale."},
            {"type": "rich", "title": "Come rileggere la lista dopo una patch", "paragraphs": [
                "Non spostare una classe dopo un solo video. Controlla se il cambiamento riguarda danno, sopravvivenza, portata, ricariche o il modo in cui la classe entra ed esce dal combattimento. Una piccola cifra puo contare meno di una nuova interazione.",
                "Prova la classe nella modalita che vuoi giocare. Una pulizia piu veloce in solo non aumenta automaticamente il valore di squadra, mentre un cambiamento di controllo puo diventare forte con compagni coordinati. Per questo la pagina separa solo, duo e squadra.",
                "Se due opzioni sono vicine, scegli il ruolo che manca e annota il risultato. Un esperienza spiegabile e piu utile di un ranking senza contesto. Aggiorneremo la pagina con note ufficiali o prove di gameplay ripetute e comprensibili.",
            ]},
            {"type": "faq", "title": "FAQ della tier list Mistfall Hunter", "items": [["Qual e la classe migliore di Mistfall Hunter?", "Mercenary e il punto di partenza piu sicuro in solo; Withered Knight e Seer salgono quando il gruppo ha bisogno di ancora o informazioni. La scelta dipende dalla modalita e dal ruolo assente."], ["Qual e la classe migliore per il solo?", "Inizia con Mercenary per una rotta permissiva. Blackarrow o Shadowstrix possono essere migliori se conosci gia distanza, ricognizione e ritirata."], ["Questa tier list e ufficiale?", "No. E un confronto indipendente basato su chiarezza del ruolo, tolleranza all errore, utilita di squadra e difficolta di esecuzione. Controlla sempre la versione attuale."], ["I principianti devono scegliere solo il tier S?", "No. Una classe A che capisci e con cui estrai vale piu di una S il cui timing non conosci. Usa la lista per scegliere cosa provare."], ["Dove posso confrontare le classi?", "La guida classi descrive ruoli e rischio, il build planner abbina solo, duo e squadra, mentre la guida gameplay spiega il ciclo di estrazione."]]},
            {"type": "links", "title": "Riferimento ufficiale", "items": [["Mistfall Hunter su Steam", "https://store.steampowered.com/app/3282300/Mistfall_Hunter/", "Fonte ufficiale per piattaforma e identita del prodotto.", "noopener"]]},
            {"type": "related", "title": "Guide Mistfall Hunter correlate", "items": [["Guida classi Mistfall Hunter", "/it/classes/", "Confronta ruoli, rischio e direzioni per principianti."], ["Planner build Mistfall Hunter", "/it/build-planner/", "Abbina la classe a solo, duo o squadra."], ["Guida gameplay Mistfall Hunter", "/it/gameplay/", "Capisci il ciclo di estrazione dietro alle scelte."], ["Review Mistfall Hunter", "/it/review/", "Leggi i compromessi del gioco e dell acquisto."]]},
        ],
    },
}

# Keep locale-specific UI terms natural for strict rendered-language checks.
TIER_LIST_PAGE_DATA["es"]["sections"][3]["paragraphs"][0] = TIER_LIST_PAGE_DATA["es"]["sections"][3]["paragraphs"][0].replace("error", "fallo")
for _section in TIER_LIST_PAGE_DATA["es"]["sections"]:
    if _section["type"] == "rich":
        _section["paragraphs"] = [paragraph.replace("error", "fallo") for paragraph in _section["paragraphs"]]
for _item in TIER_LIST_PAGE_DATA["es"]["sections"][9]["items"]:
    _item[1] = _item[1].replace("error", "fallo")
TIER_LIST_PAGE_DATA["ja"]["sections"][9]["title"] = "Mistfall Hunterティアリスト よくある質問"
TIER_LIST_PAGE_DATA["fr"]["sections"][1]["paragraphs"][2] = TIER_LIST_PAGE_DATA["fr"]["sections"][1]["paragraphs"][2].replace("le guide des classes", "la fiche des classes")
TIER_LIST_PAGE_DATA["fr"]["sections"][9]["title"] = "Questions frequentes sur la tier list Mistfall Hunter"
TIER_LIST_PAGE_DATA["fr"]["sections"][9]["items"][4][1] = TIER_LIST_PAGE_DATA["fr"]["sections"][9]["items"][4][1].replace("Le guide des classes", "La page des classes").replace("le guide gameplay", "la page gameplay")
TIER_LIST_PAGE_DATA["fr"]["sections"][11]["title"] = "Ressources Mistfall Hunter associees"
TIER_LIST_PAGE_DATA["fr"]["sections"][11]["items"][0][0] = "Fiche des classes Mistfall Hunter"
TIER_LIST_PAGE_DATA["fr"]["sections"][11]["items"][2][0] = "Ressource gameplay Mistfall Hunter"
TIER_LIST_PAGE_DATA["de"]["page"]["kicker"] = "Mistfall Hunter Klassenvergleich | Aktualisiert 08/2026"
TIER_LIST_PAGE_DATA["de"]["sections"][1]["paragraphs"][2] = TIER_LIST_PAGE_DATA["de"]["sections"][1]["paragraphs"][2].replace("Klassen-Guide", "Klassen-Leitfaden")
TIER_LIST_PAGE_DATA["de"]["sections"][9]["title"] = "Häufige Fragen zur Mistfall Hunter Tier List"
TIER_LIST_PAGE_DATA["de"]["sections"][9]["items"][4][1] = TIER_LIST_PAGE_DATA["de"]["sections"][9]["items"][4][1].replace("Der Klassen-Guide", "Der Klassen-Leitfaden").replace("Gameplay-Guide", "Gameplay-Leitfaden")
TIER_LIST_PAGE_DATA["de"]["sections"][11]["title"] = "Verwandte Mistfall Hunter Leitfäden"
TIER_LIST_PAGE_DATA["de"]["sections"][11]["items"][0][0] = "Mistfall Hunter Klassen-Leitfaden"
TIER_LIST_PAGE_DATA["de"]["sections"][11]["items"][2][0] = "Mistfall Hunter Gameplay-Leitfaden"
TIER_LIST_PAGE_DATA["pt"]["sections"][9]["title"] = "Perguntas frequentes sobre a tier list de Mistfall Hunter"
TIER_LIST_PAGE_DATA["ko"]["sections"][9]["title"] = "Mistfall Hunter 티어표 자주 묻는 질문"
TIER_LIST_PAGE_DATA["it"]["sections"][9]["title"] = "Domande frequenti sulla tier list Mistfall Hunter"
TIER_LIST_PAGE_DATA["it"]["sections"][11]["title"] = "Risorse Mistfall Hunter correlate"
